### ISSUE TITLE
"PetActionID" lua error

### ISSUE THREAD

**Issue by kwonjt2001** [frozn/TipTac#216] opened 2023-03-09 05:51 UTC
**To Reproduce**
Using pet action id show and hovering over a special action ability spell in a summons spellbook causes a lua error.

![error2](https://user-images.githubusercontent.com/98691652/223931697-17cedfb7-0432-41a5-a808-398d892d31c2.jpg)

TipTac-v23.03.07-release

**Comment by frozn** [comment] 2023-03-09 21:01
Unfortunately I can't reproduce this. I think another addon is responsible for this. Can you disable your other addons one by one and find out the corresponding addon?

**Comment by kwonjt2001** [comment] 2023-03-10 19:46
It happens even if I turn off all addons and only turn on TipTac and BugSack.
Activate "Show Pet Action ID" and only occurs on special ability spells.

**Comment by frozn** [comment] 2023-03-10 20:09
I has been able to reproduce it. I haven't enabled "Show Pet Action ID"... 🙈

**Comment by frozn** [comment] 2023-03-10 20:25
I fixed it. Will be included in the next release. 👍

**Comment by kwonjt2001** [comment] 2023-03-10 21:05
> 
You are amazing. Thank you always!

**Closed** 2023-03-10 21:17 UTC
Labels: 1_bug, 2_to develop, 3_solved
