### ISSUE TITLE
lua error with battle pet tips enabled

### ISSUE THREAD

**Issue by Duderino84** [frozn/TipTac#264] opened 2023-11-10 12:36 UTC
28x SharedXML/Color.lua:61: bad argument #2 to 'format' (string expected, got nil)
[string "=[C]"]: in function `format'
[string "@SharedXML/Color.lua"]:61: in function <SharedXML/Color.lua:60>
[string "=(tail call)"]: ?
[string "@TipTac/ttStyle.lua"]:346: in function `GeneratePetLines'
[string "@TipTac/ttStyle.lua"]:419: in function `ModifyUnitTooltip'
[string "@TipTac/ttStyle.lua"]:655: in function `?'
[string "@TipTac/libs/LibFroznFunctions-1.0-15/LibFroznFunctions-1.0.lua"]:889: in function `FireGroupEvent'
[string "@TipTac/ttCore.lua"]:2647: in function `SetUnitAppearanceToTip'
[string "@TipTac/ttCore.lua"]:2750: in function `?'
[string "@TipTac/libs/LibFroznFunctions-1.0-15/LibFroznFunctions-1.0.lua"]:889: in function `FireGroupEvent'
[string "@TipTac/ttCore.lua"]:1507: in function `SetCurrentDisplayParams'
[string "@TipTac/ttCore.lua"]:1382: in function <TipTac/ttCore.lua:1381>
...
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:182: in function <SharedXML/Tooltip/TooltipDataHandler.lua:178>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:218: in function <SharedXML/Tooltip/TooltipDataHandler.lua:208>
[string "=[C]"]: in function `SetAttribute'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:243: in function <SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:389: in function <SharedXML/Tooltip/TooltipDataHandler.lua:339>
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:336: in function `ProcessInfo'
[string "@FrameXML/GameTooltip.lua"]:1092: in function `SetWorldCursor'
[string "@FrameXML/UIParent.lua"]:1484: in function <FrameXML/UIParent.lua:1407>
[string "=[C]"]: ?

Locals:
(*temporary) = "|c%s%s|r"
(*temporary) = "ffffffff"
(*temporary) = nil
(*temporary) = "string expected, got nil"

**Comment by Duderino84** [comment] 2023-11-10 12:38
It happend everytime when i mouseover an Animaltrainer like Enok or someoneelse

**Comment by Duderino84** [comment] 2023-11-10 12:40
when i disabel "special" - enable battle pet tips
then no error apear

**Comment by frozn** [comment] 2023-11-11 17:02
I can't reproduce this on my side. The color which is used here is the one in options under "Colors->Race & Creature Type Color". Is there a proper color set?

**Comment by hollo6** [comment] 2023-11-11 17:49
I'm getting this when mousing over an Argent Gruntling.

**Comment by frozn** [comment] 2023-11-11 19:02
It seems that it's currently a blizzard bug. The return values for `UnitBattlePetType()` are currently off by one and returns a value range of `0 - 9` instead if the original `1 - 10`.

Source: https://us.forums.blizzard.com/en/wow/t/lua-error-when-clicking-on-humanoid-battle-pet/1707965

This function is actually only used on blizzards side in the target frame, where the pet type is also wrong (cats will be shown as pet type elemental instead of beast).

I think I will wait a few days if blizzard will fix this.

**Comment by frozn** [comment] 2023-11-16 13:29
As of today the bug has been fixed by blizzard. Working fine now after latest update.

**Closed** 2024-01-31 19:49 UTC
Labels: 1_bug in wow, 3_solved
