### ISSUE TITLE
Error without functionality

### ISSUE THREAD

**Issue by Zasz333** [frozn/TipTac#305] opened 2024-07-24 22:52 UTC
### Describe the bug

Updated to the latest version, not seeing any change to the tooltip but errors pop up. Tooltip remains default retail tooltip.

### Steps to Reproduce

No interaction happening.

### Expected behavior

I expect the addon to use my settings again.

### Additional context

90x TipTac/modules/ttAuras.lua:54: attempt to call method 'EnumerateInactive' (a nil value)
[string "@TipTac/modules/ttAuras.lua"]:54: in function `?'
[string "@TipTac/libs/LibFroznFunctions-1.0-24/LibFroznFunctions-1.0.lua"]:1175: in function `FireGroupEvent'
[string "@TipTac/ttCore.lua"]:1448: in function `ApplyConfig'
[string "@TipTac/ttCore.lua"]:1000: in function `?'
[string "@TipTac/ttCore.lua"]:1012: in function <TipTac/ttCore.lua:1011>

Locals:
self = <table> {
 aurasPool = <table> {
 }
}
TT_CacheForFrames = <table> {
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
}
cfg = <table> {
 colorReactText6 = <table> {
 }
 hideSpecializationAndClassText = true
 classification_elite = "%s Elite"
 tipBackdropEdge = "nil"
 showMount = false
 backdropEdgeSize = 16
 showMountCollected = false
 showMountText = false
 hideFactionText = true
 powerBar = true
 anchorFrameUnitPoint = "BOTTOM"
 showAuraCooldown = false
 colorSameGuild = <table> {
 }
 tipBorderColor = <table> {
 }
 noCooldownCount = true
 t_showTalentText = false
 colorReactText5 = <table> {
 }
 classification_rare = "%s|r (Rare)"
 enableChatHoverTips = true
 colorGuildByReaction = false
 barsCondenseValues = true
 left = 610.999904
 showMountSpeed = false
 colorGuild = <table> {
 }
 reactColoredBackdrop = false
 anchorFrameUnitType = "mouse"
 classification_trivial = "%s "
 iconSize = 25
 fontFlags = "OUTLINE"
 colorReactText2 = <table> {
 }
 hidePvpText = true
 targetYouText = "<< YOU >>"
 manaBar = true
 gradientColor = <table> {
 }
 minimapConfig = <table> {
 }
 pixelPerfectBackdrop = false
 fadeTime = 0
 if_showKeystoneRewardLevel = false
 anchorFrameTipPoint = "BOTTOM"
 top = 368.000055
 optionsBottom = 556
 gradientTip = false
 if_modifyAchievementTips = false
 hideUFTipsInCombat = true
 if_showSpellIdAndRank = false
 colorReactText8 = <table> {
 }
 if_enable = false
 reactText = false
 gttScale = 1.200000
 showCurrentUnitSpeed = false
 iconAnchor = "TOP"
 t_showTalentIcon = false
 iconFaction = true
 overrideFade = true
 hideRealmText = true
 preFadeTime = 0
 optionsLeft = 9.000010
 reactIcon = false
 t_showTalents = false
 showTarget = "belowNameRealm"
 talentCacheSize = 5
 tipBackdropBG = "Interface\Buttons\WHITE8X8"
 colorNameByClass = true
 tipColor = <table> {
 }
 anchorWorldTipPoint = "BOTTOM"
 healthBarText = "value"
 colRace = "|cffffffff"
 if_modifyKeystoneTips = false
 colorReactText7 = <table> {
 }
 classification_normal = "%s "
 showTalents = false
 classification_worldboss = "%s|r (Boss)"
 iconRaid = false
 anchorWorldUnitPoint = "BOTTOM"
 reactColoredBorder = false
 factionText = false
 if_iconSize = 120.893372
 showMythicPlusDungeonScore = false
 anchorWorldTipType = "mouse"
 iconCombat = false
 if_itemQualityBorder = false
 if_showItemLevelAndId = false
 colSameGuild = "|cff43ff1e"
 colGuild = "|cff05ff3a"
 auraSize = 15
 manaBarText = "value"
 showTargetedBy = false
 if_showKeystoneAffixInfo = false
 classColoredBorder = false
 anchorFrameTipType = "mouse"
 classification_minus = "%s "
 backdropInsets = 4
 if_showAuraCaster = false
 showPlayerGender = true
 showMountIcon = false
 showMinimapIcon = false
 enableBackdrop = true
 barTexture = "Interface\AddOns\Empath-Textures\textures\Empath12"
 classification_rareelite = "+%s|r (Rare Elite)"
 anchorWorldUnitType = "mouse"
 t_enable = false
 if_showItemId = false
 reactColoredText = false
 talentOnlyInParty = false
 showGuildRank = true
 colorReactText10 = <table> {
 }
 if_showQuestLevelAndId = false
 colorRace = <table> {
 }
 colorReactText9 = <table> {
 }
 guildRankFormat = "title"
 if_showKeystoneTimeLimit = false
}
TT_ExtendedConfig = <table> {
 tipBackdrop = <table> {
 }
 tipsToModify = <table> {
 }
 customClassColors = <table> {
 }
 oldGameTooltipTextSmall = <table> {
 }
 backdropBorderColor = <table> {
 }
 defaultAnchorType = "normal"
 tipPaddingForGameTooltip = <table> {
 }
 oldGameTooltipText = <table> {
 }
 oldGameTooltipFontsRemembered = true
 defaultAnchorPoint = "BOTTOMRIGHT"
 backdropColor = <table> {
 }
 oldGameTooltipHeaderText = <table> {
 }
}
(*temporary) = nil
(*temporary) = <table> {
}
(*temporary) = "attempt to call method 'EnumerateInactive' (a nil value)"

### Version of TipTac Reborn

24.07.24

### Flavor/Version of WoW

Retail

**Comment by frozn** [comment] 2024-07-25 00:48
Thanks for reporting this! 👍

Fixed with the latest release [v24.07.25](https://github.com/frozn/TipTac/releases/tag/v24.07.25-release).

Duplicate of #303.

**Closed** 2024-07-25 00:48 UTC
Labels: 1_bug, 3_duplicate
