### ISSUE TITLE
Player names are missing from tooltips

### ISSUE THREAD

**Issue by hollo6** [frozn/TipTac#273] opened 2024-01-19 20:17 UTC
**Describe the bug**
Since 10.2.5, player tooltips from party/raid frames are missing player names, only the realm is being shown.

**To Reproduce**
1. Be in a party with somone that is out of range
2. Hover over that player on the party frame
3. Observe missing player name

**Expected behavior**
Player names should be shown regardless of distance, like before.

**Screenshots**
![image](https://github.com/frozn/TipTac/assets/365584/87fc14e8-8fc4-4047-a4c7-7a714f822635)

**TipTac Reborn (please complete the following information):**
 - Version 23.12.10

**WoW (please complete the following information):**
 - Flavor: Retail
 - Version 10.2.5

**Additional context**
Never seen this problem before 10.2.5.

**Comment by frozn** [comment] 2024-01-19 23:37
Thanks for reporting this! 👍 

Unfortunately I haven't been able to reproduce this yet. I grouped with someone and teleported somewhere out of range, but the player name is still visible.

Is this only related to dungeons/raids, because I tested this in the open world?

**Comment by hollo6** [comment] 2024-01-19 23:49
I think you should be out of range when entering the group, once you're in range, the tooltip will show the name even if you go away.

**Comment by Vilogity** [comment] 2024-01-20 21:17
Same here, join Group and only see Server Name when out of range.
The only one I see was the druid he was also in valdraken.
Never had this before !!

**Comment by DaleHuntGB** [comment] 2024-01-21 09:28
This happened to me as well.

Out of Range Players just return nothing at all.

My assumption, because there's no error, it is likely to do with either determining class colour and failing so the string is just empty or it'll be something weird with server name.

Other than that, not entirely sure what's happening but as I said, no errors when hovering over the players, just returns a blank string (that's what it seems like).

**Comment by hollo6** [comment] 2024-01-21 10:45
> The only one I see was the druid he was also in valdraken.
>Is this only related to dungeons/raids, because I tested this in the open world?
>For me yes

Then the answer is no because Valdrakken is open world, not a dungeon or raid.


> My assumption, because there's no error, it is likely to do with either determining class colour and failing so the string is just empty or it'll be something weird with server name.

It's not class color, the borders and text are always shown and colored correctly, just like in my screenshot above.
And it is not just one server name, it's ALL server names - also, even if there is no server name because the player is from the same realm, their name is missing just as well. In that case the first line in the tooltip is just blank.

**Comment by Vilogity** [comment] 2024-01-21 13:36
> > The only one I see was the druid he was also in valdraken.
> > Is this only related to dungeons/raids, because I tested this in the open world?
> > For me yes
> 
> Then the answer is no because Valdrakken is open world, not a dungeon or raid.
> 
> > My assumption, because there's no error, it is likely to do with either determining class colour and failing so the string is just empty or it'll be something weird with server name.
> 
> It's not class color, the borders and text are always shown and colored correctly, just like in my screenshot above. And it is not just one server name, it's ALL server names - also, even if there is no server name because the player is from the same realm, their name is missing just as well. In that case the first line in the tooltip is just blank.

I mean this is only happen to me when I join Group.......the druide from the Group was in my near.
Today I see IN Group........nothing...no name or Server, then when we all together in Instance all ok.

**Comment by frozn** [comment] 2024-01-21 23:22
What do you have set in options under "General->Name & Title"?

I'm currently "under heavy development" regarding some other issues with df patch 10.2.5 and jumped into playing more WoW again after a sidetrip to Diablo IV. So I will further try to reproduce this. 🙂

**Comment by hollo6** [comment] 2024-01-21 23:39
> What do you have set in options under "General->Name & Title"?

Name + title.

But this happens for everyone, regardless if they have a title shown or not.

**Comment by Vilogity** [comment] 2024-01-28 05:29
For me, it's allways there.......
Allways when joining a Group.

**Comment by frozn** [comment] 2024-01-31 19:30
Thanks @DaleHuntGB for this hint!

I have been able to reproduce this with a random world quest group. The missing unit name is only an issue if "General->Name & Title" has been set to "Name + title". In this case api function `UnitPVPName()` returns `nil` or `""` for unit's name with title. Because I always play with "Name only", I haven't noticed this yet. Here the unit name will be determined with `UnitName()`, which always returns a valid unit name.

Fix will be included in the next release! 👍

**Comment by hollo6** [comment] 2024-01-31 21:58
Looks good now, thanks!

**Closed** 2024-03-17 21:18 UTC
Labels: 1_bug, 2_to develop, 3_solved
