### ISSUE TITLE
ttCore.lua:1680: Attempt to access forbidden object from code tainted by an AddOn

### ISSUE THREAD

**Issue by Ookami313** [frozn/TipTac#85] opened 2022-06-18 01:49 UTC
Running latest version. Mousing over a Stone Soup pot as the 'feast' is being created produces the following error. Thanks.

4x TipTac\ttCore.lua:1680: Attempt to access forbidden object from code tainted by an AddOn
[string "=[C]"]: in function `GetParent'
[string "@TipTac\ttCore.lua"]:1680: in function `SetCenterColor'
[string "@SharedXML\SharedTooltipTemplates.lua"]:52: in function <SharedXML\SharedTooltipTemplates.lua:41>
[string "=[C]"]: in function `SharedTooltip_SetBackdropStyle'
[string "@FrameXML\GameTooltip.lua"]:404: in function <FrameXML\GameTooltip.lua:400>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Hide'
[string "@Blizzard_UIWidgets\Blizzard_UIWidgetTemplateBase.lua"]:109: in function `OnLeave'
[string "@Blizzard_UIWidgets\Blizzard_UIWidgetTemplateBase.lua"]:594: in function <...Blizzard_UIWidgets\Blizzard_UIWidgetTemplateBase.lua:593>

Locals:
(*temporary) = <unnamed> {
 BottomLeftCorner = <unnamed> {
 }
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:144
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:382
 SetBackdropBorderColor = <function> defined @TipTac\ttCore.lua:1671
 RightEdge = <unnamed> {
 }
 BottomEdge = <unnamed> {
 }
 SetBackdrop = <function> defined @TipTac\ttCore.lua:1655
 GetCenterColor = <function> defined @SharedXML\NineSlice.lua:231
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:401
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:339
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:258
 SetCenterColor = <function> defined @TipTac\ttCore.lua:1679
 GetFrameLayoutTextureKit = <function> defined @SharedXML\NineSlice.lua:213
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:206
 GetBorderColor = <function> defined @SharedXML\NineSlice.lua:249
 TopRightCorner = <unnamed> {
 }
 0 = <userdata>
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:180
 SetupPieceVisuals = <function> defined @SharedXML\Backdrop.lua:238
 OnLoad = <function> defined @SharedXML\NineSlice.lua:217
 TopEdge = <unnamed> {
 }
 ApplyBackdrop = <function> defined @TipTac\ttCore.lua:1647
 SetBorderColor = <function> defined @TipTac\ttCore.lua:1687
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:270
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:174
 Center = <unnamed> {
 }
 TopLeftCorner = <unnamed> {
 }
 GetFrameLayoutType = <function> defined @SharedXML\NineSlice.lua:209
 BottomRightCorner = <unnamed> {
 }
 SetBackdropColor = <function> defined @TipTac\ttCore.lua:1663
 LeftEdge = <unnamed> {
 }
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:274
}

**Comment by frozn** [comment] 2022-07-05 18:47
Duplicate of #80.

**Comment by frozn** [comment] 2023-01-23 22:48
Should be fixed with latest release [v23.01.23](https://github.com/frozn/TipTac/releases/tag/v23.01.23-release). Please try again with this version.

**Closed** 2023-03-07 22:40 UTC
Labels: 1_bug, 2_to develop, 3_solved
