### ISSUE TITLE
Please update addon for WOW ver 11.0.2 thanks 

### ISSUE THREAD

**Issue by z78929999** [frozn/TipTac#334] opened 2024-08-16 14:24 UTC
### Describe the bug

30x TipTacItemRef/libs/LibItemString.lua:321: attempt to call field 'SurfaceArgs' (a nil value)
[string "@TipTacItemRef/libs/LibItemString.lua"]:321: in function <TipTacItemRef/libs/LibItemString.lua:316>
[string "=(tail call)"]: ?
[string "@TipTacItemRef/ttItemRef.lua"]:2417: in function `item'
[string "@TipTacItemRef/ttItemRef.lua"]:1406: in function <TipTacItemRef/ttItemRef.lua:1396>
[string "=[C]"]: in function `EmbeddedItemTooltip_SetItemByID'
[string "@Blizzard_PVPUI/Blizzard_PVPUI.lua"]:1607: in function <Blizzard_PVPUI/Blizzard_PVPUI.lua:1588>

Locals:
self = <table> {
 ITEM_LEVEL_PATTERN = "物品等級(%d+)"
 ITEMSTRING_PROPERTY_INDEX = <table> {
 }
 TIMEWARPED_LEVEL_ADJUST = <table> {
 }
 UPGRADED_LEVEL_ADJUST = <table> {
 }
 ITEMSTRING_PATTERN = "(item:[^|]+)"
 ScanTip = LibItemStringScanTip {
 }
 TOOLTIP_MAXLINE_LEVEL = 5
 REVISION = 4
 TIMEWARPED_WARFORGED_LEVEL_ADJUST = <table> {
 }
}
itemLink = "|cffa335ee|Hitem:201250::::::::70:71:::::::::|h[凱旋爭奪者的保險箱]|h|r"
tooltipData = <table> {
 dataInstanceID = 1681
 type = 0
 isAzeriteEmpoweredItem = false
 isAzeriteItem = false
 id = 201250
 hyperlink = "|cffa335ee|Hitem:201250::::::::70:71:::::::::|h[凱旋爭奪者的保險箱]|h|r"
 isCorruptedItem = false
 lines = <table> {
 }
}
(*temporary) = nil
(*temporary) = <table> {
 dataInstanceID = 1681
 type = 0
 isAzeriteEmpoweredItem = false
 isAzeriteItem = false
 id = 201250
 hyperlink = "|cffa335ee|Hitem:201250::::::::70:71:::::::::|h[凱旋爭奪者的保險箱]|h|r"
 isCorruptedItem = false
 lines = <table> {
 }
}
(*temporary) = "attempt to call field 'SurfaceArgs' (a nil value)"
LIS = <table> {
 ITEM_LEVEL_PATTERN = "物品等級(%d+)"
 ITEMSTRING_PROPERTY_INDEX = <table> {
 }
 TIMEWARPED_LEVEL_ADJUST = <table> {
 }
 UPGRADED_LEVEL_ADJUST = <table> {
 }
 ITEMSTRING_PATTERN = "(item:[^|]+)"
 ScanTip = LibItemStringScanTip {
 }
 TOOLTIP_MAXLINE_LEVEL = 5
 REVISION = 4
 TIMEWARPED_WARFORGED_LEVEL_ADJUST = <table> {
 }
}

### Version of TipTac Reborn

9.5.1

### Flavor/Version of WoW

11.0.2.56110

**Comment by Wraithlord2015** [comment] 2024-08-17 21:42
API depreciation: The C_TooltipInfo APIs now return data with all data and line arguments surfaced, removing the need to call TooltipUtil.SurfaceArgs()

Not sure how the addon dev wants to handle it, but I just simply commented out line 37 in TipTacItemRef/libs/LibItemString.lua:

Change line 37:

From
TooltipUtil.SurfaceArgs(line);

To
-- TooltipUtil.SurfaceArgs(line);

**Comment by frozn** [comment] 2024-08-19 00:12
Thanks for reporting this! 👍

Calling `TooltipUtil.SurfaceArgs()` is obsolete (since df 10.1.0) and can be removed. The fix will be included in the next release.

Duplicate of #330.

**Closed** 2024-08-19 00:13 UTC
Labels: 1_bug, 3_duplicate
