### ISSUE TITLE
Bartender4 Related Issue

### ISSUE THREAD

**Issue by Spiderkeg** [frozn/TipTac#314] opened 2024-07-26 22:03 UTC
### Describe the bug

I am using Bartender4.

I've noticed that when hovering over an EMPTY button, then hover over a unit (player, NPC, etc.) the tooltip will either reset to wherever the GameTooltip anchor is or (if anchored to mouse) will show with all colors stripped out.

### Steps to Reproduce

I'd love to see if anyone else can confirm.

### Expected behavior

Expected Behavior: have the tooltip to work.

### Additional context

Not sure how this can be addressed, considering this involves another addon, but I did find a clunky solution.  This will require Masque to also be installed.

LibActionButton-1.0.lua, under the Generic:OnEnter() function.  I wrapped the UpdateTooltip(self) in a condition.

if not self.__MSQ_Empty then
	UpdateTooltip(self)
end

This is merely checking to see if the button is empty, updating the tooltip only if the button has an icon.  So far in my testing, this is fixing the issue, albeit clunky.

### Version of TipTac Reborn

24.07.26

### Flavor/Version of WoW

War Within Patch, 11.0.0

**Comment by frozn** [comment] 2024-07-26 22:53
Thanks for reporting this! 👍

I could reproduce this issue and it's really strange... I thought I have seen everything, but that's not true. 😅

**Comment by Spiderkeg** [comment] 2024-07-27 07:02
> Thanks for reporting this! 👍
> 
> I could reproduce this issue and it's really strange... I thought I have seen everything, but that's not true. 😅

Good that you could reproduce the issue.  Bad that it's a thing.  Out of curiosity, do you have any theories?

**Comment by frozn** [comment] 2024-07-27 16:28
I have been able to fix this.

The internal tip status, which is tracked in TipTac, handled the situation regarding empty action bar buttons slightly wrong. If hovering over an empty button, the function `GameTooltip:SetAction()` is called regardless if it's empty or not. Because the tooltip will never appear, there's will be no hide event later if moving the mouse away. That causes issues for the next tooltip which will be triggered. Totally easy! 😅

Fix will be included in the next release.

**Comment by frozn** [comment] 2024-07-27 16:31
I've noticed this error myself in the past, but since it always occurred completely randomly and I didn't recognize any patterns, I haven't been able to investigate it any further except now.

**Closed** 2024-08-06 11:39 UTC
Labels: 1_bug, 2_to develop, 3_solved
