### ISSUE TITLE
Layout seems to not work

### ISSUE THREAD

**Issue by KonstantinosKoubetsos** [frozn/TipTac#107] opened 2022-10-26 10:27 UTC
Logged to day with the prepatch UI changes and it seems tiptac layout has changed. I tried picking again from Layout template "Tiptac new style" but it won't change to how it was before.

**Comment by frozn** [comment] 2022-10-30 18:58
I'm on it, but haven't found a solution yet...

**Comment by frozn** [comment] 2022-11-03 21:54
Probably same problem with hidden scanning tooltips like here: #116

**Comment by KonstantinosKoubetsos** [comment] 2022-11-04 08:27
So with the new patch API mentioned in that post this will be fixed?

**Comment by frozn** [comment] 2022-11-04 10:27
I don't know. I created a ticket for blizzard and wait for a reply on this topic. Currently, every addon which uses a hidden scanning tooltip to e.g. retrieve informations about an item will have an impact on the actual displaying tooltip (content disappears, coin icons move away, level and race can't be modified).

On TipTac's side I can't prevent this actually... 👎

**Comment by Invarix** [comment] 2022-11-04 16:11
I receive this error when attempting to access any layout customizations at all:

Message: FontString:SetFormattedText(): Font not set
Count: 41
Stack: FontString:SetFormattedText(): Font not set
[string "=[C]"]: in function `SetFormattedText'
[string "@Interface/AddOns/TipTac/ttBars.lua"]:151: in function `SetFormattedBarValues'
[string "@Interface/AddOns/TipTac/ttBars.lua"]:256: in function `?'
[string "@Interface/AddOns/TipTac/ttCore.lua"]:298: in function `SendElementEvent'
[string "@Interface/AddOns/TipTac/ttCore.lua"]:631: in function `ApplyUnitAppearance'
[string "@Interface/AddOns/TipTac/ttCore.lua"]:819: in function <Interface/AddOns/TipTac/ttCore.lua:780>
[string "=[C]"]: ?

Locals: (*temporary) = FontString {
 0 = <userdata>
}
(*temporary) = "%s / %s"
(*temporary) = "67.0k"
(*temporary) = "67.0k"

**Comment by frozn** [comment] 2022-11-04 18:25
@Invarix: Possibly related to [this](https://github.com/frozn/TipTac/issues/123#issuecomment-1303974939), cause you're using on outdated version of TipTac.

**Comment by frozn** [comment] 2022-11-14 00:37
Summary:
The issue with the sometimes blank tooltips currently is caused by other addons using a hidden scanning tooltip to determine informations about items/spells etc. and is a bug in the current wow patch 10.0.0. This will be fixed with the upcoming wow patch 10.0.2 (currently on PTR, works fine here).

Additionally the styling of level, class and race in tooltip line 3 for players in a guild doesn't also work in this case under patch 10.0.0.

**Closed** 2022-11-14 00:38 UTC
Labels: 1_bug in wow, 3_solved
