### ISSUE TITLE
Tooltip will Occasionally Popup in Wrong Location

### ISSUE THREAD

**Issue by Spiderkeg** [frozn/TipTac#220] opened 2023-04-21 20:51 UTC
**Describe the bug**
Occasionally, the tooltip will reset to an stationary anchored position, even though mouse/frame anchors are
![image_2023-04-21_164957443](https://user-images.githubusercontent.com/3663456/233732315-7da26b8c-26e8-4daa-89e0-9f58cad36f78.png)
 being used.  The tooltip will correct itself once the mouse hovers over an action button or bag slot.

**To Reproduce**
I notice this mostly when I have my bag open, my mouse is currently over the action bar, and I quickly move from action bar button to bag slot.  The mouse, now over a bag slot, will show the tooltip shifted over as if the x/y coords have changed.  Moving the mouse again will jolt the tooltip into following the mouse again.

In the provided screenshot, I am using Bartender 4, Masque (which loads with Bartender4 by default), and LiteBag.

**Comment by Spiderkeg** [comment] 2023-04-21 20:53
Note: the screenshot doesn't show the location of the mouse cursor, but the cursor was hovering over the Battle Standard of Coordination shown in the bag.  The tooltip should be anchored to the left of the bag slot, but clearly the tooltip is showing x/y pushed over further.

**Comment by frozn** [comment] 2023-04-24 17:12
Thanks for reporting this issue! 👍 

Will be fixed with the next release. Duplicate of #221.

**Closed** 2023-05-07 18:26 UTC
Labels: 1_bug, 3_duplicate
