### ISSUE TITLE
lua error - bartender blank tooltip

### ISSUE THREAD

**Issue by Dubwize** [frozn/TipTac#123] opened 2022-11-04 16:04 UTC
Using the newest version.  when mosuing over some icons on bartender.  you get a blank tooltip.  lua and image below.

![image](https://user-images.githubusercontent.com/16105140/200022107-42fe6ae9-b229-4dd0-9389-423b782f7b76.png)

94x Interface/FrameXML/GameTooltip.lua:190: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: GameTooltip:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@Interface/FrameXML/GameTooltip.lua"]:190: in function <Interface/FrameXML/GameTooltip.lua:172>
[string "=[C]"]: in function `GameTooltip_SetDefaultAnchor'
[string "@Interface/AddOns/Bartender4/libs/LibActionButton-1.0-96/LibActionButton-1.0.lua"]:1455: in function `UpdateTooltip'
[string "@Interface/FrameXML/GameTooltip.lua"]:498: in function <Interface/FrameXML/GameTooltip.lua:485>
[string "=[C]"]: ?

Locals:
(*temporary) = GameTooltip {
 0 = <userdata>
 SetQuestPartyProgress = <function> defined =[C]:-1
 ttNumLines = 0
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 SetExistingSocketGem = <function> defined =[C]:-1
 SetHyperlink = <function> defined =[C]:-1
 SetUnit = <function> defined =[C]:-1
 SetAzeriteEssence = <function> defined =[C]:-1
 ttBackdropBorderColorApplied = false
 SetVoidWithdrawalItem = <function> defined =[C]:-1
 ttSetBackdropBorderColorLocked = true
 SetSocketGem = <function> defined =[C]:-1
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 Show = <function> defined =[C]:-1
 SetPetAction = <function> defined =[C]:-1
 SetEnhancedConduit = <function> defined =[C]:-1
 SetLFGDungeonReward = <function> defined =[C]:-1
 ttDefaultAnchored = false
 ApplyBackdrop = <function> defined @Interface/AddOns/TipTac/ttCore.lua:1636
 FadeOut = <function> defined @Interface/AddOns/TipTac/ttCore.lua:1449
 numMoneyFrames = 1
 BottomLeftCorner = Texture {
 }
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetQuestCurrency = <function> defined =[C]:-1
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 SetWeeklyReward = <function> defined =[C]:-1
 SetCurrencyTokenByID = <function> defined =[C]:-1
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 SetVoidDepositItem = <function> defined =[C]:-1
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 ttUnit = <table> {
 }
 comparing = false
 SetLootItem = <function> defined =[C]:-1
 ttIcon = Texture {
 }
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 NineSlice = Frame {
 }
 SetCompanionPet = <function> defined =[C]:-1
 TopEdge = Texture {
 }
 ttCount = FontString {
 }
 SetLootRollItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 ItemTooltip = Frame {
 }
 SetBagItem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined =[C]:-1
 BottomRightCorner = Texture {
 }
 SetBackdropColor = <function> defined @Interface/AddOns/TipTac/ttCore.lua:1652
 LeftEdge = Texture {
 }
 RightEdge = Texture {
 }
 TopRightCorner = Texture {
 }
 SetCurrencyByID = <function> defined =[C]:-1
 ttLastUpdate = 0
 ttSetIconTextureAndText = <function> defined @Interface/AddOns/TipTacItemRef/ttItemRef.lua:191
 hasMoney = 1
 SetSpellBookItem = <function> defined =[C]:-1
 ttBackdropColorApplied = false
 textLeft1Font = "GameTooltipHeaderText"
 SetInventoryItem = <function> defined =[C]:-1
 SetConduit = <function> defined =[C]:-1
 SetCurrencyToken = <function> defined =[C]:-1
 SetGuildBankItem = <function> defined =[C]:-1
 SetVoidItem = <function> defined =[C]:-1
 SetBackdropBorderColor = <function> defined @Interface/AddOns/TipTac/ttCore.lua:1660
 SetAction = <function> defined =[C]:-1
 Hide = <function> defined =[C]:-1
 ttDisplayingUnit = false
 waitingForData = false
 ttDisplayingAura = false
 textRight2Font = "GameTooltipText"
 BottomOverlay = Texture {
 }
 BottomEdge = Texture {
 }
 SetBackdrop = <function> defined @Interface/AddOns/TipTac/ttCore.lua:1644
 updateTooltipTimer = 0.200000
 TopOverlay = Texture {
 }
 GetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:347
 SetUnitDebuff = <function> defined =[C]:-1
 SetItemByID = <function> defined =[C]:-1
 TopLeftCorner = Texture {
 }
 SetQuestItem = <function> defined =[C]:-1
 ttAnchorType = "normal"
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
 SetToyByItemID = <function> defined =[C]:-1
 TextLeft1 = GameTooltipTextLeft1 {
 }
 TextRight1 = GameTooltipTextRight1 {
 }
 SetTrainerService = <function> defined =[C]:-1
 SetInboxItem = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 SetHeirloomByItemID = <function> defined =[C]:-1
 SetLFGDungeonShortageReward = <function> defined =[C]:-1
 backdropInfo = <table> {
 }
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 SetUnitBuff = <function>

**Comment by Dubwize** [comment] 2022-11-04 16:05
Also happens with the tooltip for the "Game Menu" icon mouseover

**Comment by Invarix** [comment] 2022-11-04 16:09
Getting this from any mouseover action. Possibly related:

> Message: TipTac:RegisterEvent(): TipTac:RegisterEvent(): Attempt to register unknown event "CURSOR_UPDATE"
Count: 1
Stack: TipTac:RegisterEvent(): TipTac:RegisterEvent(): Attempt to register unknown event "CURSOR_UPDATE"
[string "=[C]"]: in function `RegisterEvent'
[string "@Interface/AddOns/TipTac/ttCore.lua"]:473: in function `ApplySettings'
[string "@Interface/AddOns/TipTac/ttCore.lua"]:383: in function `?'
[string "@Interface/AddOns/TipTac/ttCore.lua"]:403: in function <Interface/AddOns/TipTac/ttCore.lua:403>

>Locals: (*temporary) = TipTac {
 CreatePushArray = <function> defined @Interface/AddOns/TipTac/ttCore.lua:269
 elements = <table> {
 }
 ClassColorMarkup = <table> {
 }
 AddModifiedTip = <function> defined @Interface/AddOns/TipTac/ttCore.lua:947
 MirrorAnchorsSmart = <table> {
 }
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 VARIABLES_LOADED = <function> defined @Interface/AddOns/TipTac/ttCore.lua:349
 TopLeftCorner = Texture {
 }
 RightEdge = Texture {
 }
 CVAR_UPDATE = <function> defined @Interface/AddOns/TipTac/ttCore.lua:395
 u = <table> {
 }
 ApplyBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 GetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:347
 isColorBlind = false
 ApplyUnitAppearance = <function> defined @Interface/AddOns/TipTac/ttCore.lua:621
 BottomEdge = Texture {
 }
 CURSOR_UPDATE = <function> defined @Interface/AddOns/TipTac/ttCore.lua:327
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
 AnchorFrameToMouse = <function> defined @Interface/AddOns/TipTac/ttCore.lua:528
 MirrorAnchors = <table> {
 }
 RegisterElement = <function> defined @Interface/AddOns/TipTac/ttCore.lua:289
 PLAYER_LOGIN = <function> defined @Interface/AddOns/TipTac/ttCore.lua:337
 PLAYER_LEVEL_UP = <function> defined @Interface/AddOns/TipTac/ttCore.lua:344
 RemoveUnwantedLines = <function> defined @Interface/AddOns/TipTac/ttCore.lua:537
 0 = <userdata>
 yPadding = 0
 tipsToModify = <table> {
 }
 backdropInfo = <table> {
 }
 SendElementEvent = <function> defined @Interface/AddOns/TipTac/ttCore.lua:295
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 text = FontString {
 }
 GetUnitReactionIndex = <function> defined @Interface/AddOns/TipTac/ttCore.lua:567
 close = Button {
 }
 ApplySettings = <function> defined @Interface/AddOns/TipTac/ttCore.lua:470
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 Center = Texture {
 }
 SetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:422
 TopEdge = Texture {
 }
 AddTargetedBy = <function> defined @Interface/AddOns/TipTac/ttCore.lua:593
 ApplyTipBackdrop = <function> defined @Interface/AddOns/TipTac/ttCore.lua:519
 BottomRightCorner = Texture {
 }
 BottomLeftCorner = Texture {
 }
 TopRightCorner = Texture {
 }
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 SetupPieceVisuals = <function> defined @Interface/SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:399
 LeftEdge = Texture {
 }
 xPadding = 0
}
(*temporary) = "CURSOR_UPDATE"

**Comment by frozn** [comment] 2022-11-04 18:21
@Invarix: The reason for your error regarding event CURSOR_UPDATE is, that you're using the old version v20.11.04 instead the latest release. Check version in options `/tiptac` (top right).

**Comment by frozn** [comment] 2022-11-05 00:27
@Dubwize: Please try this possible fix, see here: https://github.com/frozn/TipTac/issues/77#issuecomment-1302511027

**Comment by Invarix** [comment] 2022-11-05 00:44
> @Invarix: The reason for your error regarding event CURSOR_UPDATE is, that you're using the old version v20.11.04 instead the latest release. Check version in options `/tiptac` (top right).

Confirmed an old version. The latest release resolve this issue.

**Comment by frozn** [comment] 2022-11-05 01:03
That are good news! @Invarix 🥳

**Comment by BlueNightSky** [comment] 2022-11-05 14:15
Both Bartender and TipTac both used the latest version, but there were still errors:
`9x Interface/FrameXML/GameTooltip.lua:190: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: GameTooltip:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@Interface/FrameXML/GameTooltip.lua"]:190: in function <Interface/FrameXML/GameTooltip.lua:172>
[string "=[C]"]: in function `GameTooltip_SetDefaultAnchor'
[string "*GameTooltip.xml:25_OnTooltipSetDefaultAnchor"]:1: in function <[string "*GameTooltip.xml:25_OnTooltipSetDefaultAnch..."]:1>

Locals:
(*temporary) = GameTooltip {
 0 = <userdata>
 SetQuestPartyProgress = <function> defined =[C]:-1
 ttNumLines = 0
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 ItemTooltip = Frame {
 }
 SetHyperlink = <function> defined =[C]:-1
 SetUnit = <function> defined =[C]:-1
 SetAzeriteEssence = <function> defined =[C]:-1
 RightEdge = Texture {
 }
 ttSetBackdropBorderColorLocked = true
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 Show = <function> defined =[C]:-1
 hasMoney = 1
 SetPetAction = <function> defined =[C]:-1
 SetLootItem = <function> defined =[C]:-1
 ttDefaultAnchored = false
 FadeOut = <function> defined @Interface/AddOns/TipTac/ttCore.lua:1460
 numMoneyFrames = 2
 SetBackpackToken = <function> defined =[C]:-1
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 SetMerchantItem = <function> defined =[C]:-1
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 ttUnit = <table> {
 }
 BottomLeftCorner = Texture {
 }
 ttWorkaroundForFirstMouseoverStatus = 0
 ttIcon = Texture {
 }
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 NineSlice = Frame {
 }
 SetInventoryItem = <function> defined =[C]:-1
 TopEdge = Texture {
 }
 ttCount = FontString {
 }
 SetLootRollItem = <function> defined =[C]:-1
 ttBackdropBorderColorApplied = false
 SetLFGDungeonReward = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 ttGradient = Texture {
 }
 BottomRightCorner = Texture {
 }
 SetBackdropColor = <function> defined @Interface/AddOns/TipTac/ttCore.lua:1663
 LeftEdge = Texture {
 }
 TextRight1 = GameTooltipTextRight1 {
 }
 SetQuestCurrency = <function> defined =[C]:-1
 SetCurrencyByID = <function> defined =[C]:-1
 SetCurrencyTokenByID = <function> defined =[C]:-1
 ttSetIconTextureAndText = <function> defined @Interface/AddOns/TipTacItemRef/ttItemRef.lua:191
 SetMerchantCostItem = <function> defined =[C]:-1
 SetSpellBookItem = <function> defined =[C]:-1
 TopRightCorner = Texture {
 }
 textLeft1Font = "GameTooltipHeaderText"
 ttLastUpdate = 0
 ttBackdropColorApplied = false
 SetCurrencyToken = <function> defined =[C]:-1
 SetGuildBankItem = <function> defined =[C]:-1
 updateTooltipTimer = 0.124000
 SetBackdropBorderColor = <function> defined @Interface/AddOns/TipTac/ttCore.lua:1671
 SetCompanionPet = <function> defined =[C]:-1
 ttAnchorType = "normal"
 ttDisplayingUnit = false
 SetAction = <function> defined =[C]:-1
 comparing = false
 ttDisplayingAura = false
 BottomOverlay = Texture {
 }
 ClearLines = <function> defined =[C]:-1
 SetBackdrop = <function> defined @Interface/AddOns/TipTac/ttCore.lua:1655
 waitingForData = false
 TopOverlay = Texture {
 }
 GetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:347
 SetUnitDebuff = <function> defined =[C]:-1
 SetItemByID = <function> defined =[C]:-1
 TopLeftCorner = Texture {
 }
 SetQuestItem = <function> defined =[C]:-1
 __tooltipUpdated = false
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
 SetToyByItemID = <function> defined =[C]:-1
 textRight2Font = "GameTooltipText"
 BottomEdge = Texture {
 }
 ApplyBackdrop = <function> defined @Interface/AddOns/TipTac/ttCore.lua:1647
 SetInboxItem = <function> defined =[C]:-1
 TextLeft1 = GameTooltipTextLeft1 {
 }
 SetAzeriteEssenceSlot = <function> defined =[C]:-1
 SetLFGDungeonShortageReward = <function> defined =[C]:-1
 SetQuestLogItem = <function> defined =[C]:-1
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 SetUnitBuff = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 SetTradePlayerItem = <function> defined =[C]:-1
 textRight1Font = "GameTooltipHeaderText"
 SetSendMailItem = <function> defined =[C]:-1
 ttSetBackdropLocked = true
 SetEnhancedConduit = <f`

**Comment by BlueNightSky** [comment] 2022-11-05 15:08
I closed Bartender4, but I still jumped out of this error, using the latest version of v22.11.04

`1x Interface/FrameXML/GameTooltip.lua:190: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: GameTooltip:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@Interface/FrameXML/GameTooltip.lua"]:190: in function <Interface/FrameXML/GameTooltip.lua:172>
[string "=[C]"]: in function `GameTooltip_SetDefaultAnchor'
[string "@Interface/FrameXML/ActionButton.lua"]:899: in function `SetTooltip'
[string "@Interface/FrameXML/ActionButton.lua"]:834: in function `OnEvent'
[string "@Interface/FrameXML/ActionButton.lua"]:216: in function <Interface/FrameXML/ActionButton.lua:213>

Locals:
(*temporary) = GameTooltip {
 0 = <userdata>
 SetQuestPartyProgress = <function> defined =[C]:-1
 ttNumLines = 0
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 ItemTooltip = Frame {
 }
 SetHyperlink = <function> defined =[C]:-1
 SetUnit = <function> defined =[C]:-1
 SetAzeriteEssence = <function> defined =[C]:-1
 RightEdge = Texture {
 }
 ttSetBackdropBorderColorLocked = true
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 Show = <function> defined =[C]:-1
 SetPetAction = <function> defined =[C]:-1
 SetLootItem = <function> defined =[C]:-1
 ttDefaultAnchored = false
 FadeOut = <function> defined @Interface/AddOns/TipTac/ttCore.lua:1460
 numMoneyFrames = 4
 ttBackdropBorderColorApplied = false
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 SetBackpackToken = <function> defined =[C]:-1
 SetMerchantItem = <function> defined =[C]:-1
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 BottomLeftCorner = Texture {
 }
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 ttUnit = <table> {
 }
 ttWorkaroundForFirstMouseoverStatus = 0
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 ttIcon = Texture {
 }
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 NineSlice = Frame {
 }
 SetInventoryItem = <function> defined =[C]:-1
 TopEdge = Texture {
 }
 ttCount = FontString {
 }
 SetLootRollItem = <function> defined =[C]:-1
 SetLFGDungeonReward = <function> defined =[C]:-1
 ttGradient = Texture {
 }
 SetBagItem = <function> defined =[C]:-1
 SetQuestCurrency = <function> defined =[C]:-1
 BottomRightCorner = Texture {
 }
 SetBackdropColor = <function> defined @Interface/AddOns/TipTac/ttCore.lua:1663
 LeftEdge = Texture {
 }
 TextRight1 = GameTooltipTextRight1 {
 }
 SetCurrencyTokenByID = <function> defined =[C]:-1
 SetCurrencyByID = <function> defined =[C]:-1
 SetMerchantCostItem = <function> defined =[C]:-1
 ttSetIconTextureAndText = <function> defined @Interface/AddOns/TipTacItemRef/ttItemRef.lua:191
 TopRightCorner = Texture {
 }
 SetSpellBookItem = <function> defined =[C]:-1
 ttLastUpdate = 0
 textLeft1Font = "GameTooltipHeaderText"
 ttBackdropColorApplied = false
 SetCompanionPet = <function> defined =[C]:-1
 SetCurrencyToken = <function> defined =[C]:-1
 SetGuildBankItem = <function> defined =[C]:-1
 updateTooltipTimer = 0.029000
 SetBackdropBorderColor = <function> defined @Interface/AddOns/TipTac/ttCore.lua:1671
 SetAction = <function> defined =[C]:-1
 ttAnchorType = "normal"
 ttDisplayingUnit = false
 hasMoney = 1
 comparing = false
 ttDisplayingAura = false
 BottomOverlay = Texture {
 }
 ClearLines = <function> defined =[C]:-1
 SetBackdrop = <function> defined @Interface/AddOns/TipTac/ttCore.lua:1655
 waitingForData = false
 TopOverlay = Texture {
 }
 GetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:347
 SetUnitDebuff = <function> defined =[C]:-1
 SetItemByID = <function> defined =[C]:-1
 TopLeftCorner = Texture {
 }
 SetQuestItem = <function> defined =[C]:-1
 __tooltipUpdated = false
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
 SetToyByItemID = <function> defined =[C]:-1
 textRight2Font = "GameTooltipText"
 BottomEdge = Texture {
 }
 ApplyBackdrop = <function> defined @Interface/AddOns/TipTac/ttCore.lua:1647
 SetInboxItem = <function> defined =[C]:-1
 TextLeft1 = GameTooltipTextLeft1 {
 }
 SetAzeriteEssenceSlot = <function> defined =[C]:-1
 SetLFGDungeonShortageReward = <function> defined =[C]:-1
 SetQuestLogItem = <function> defined =[C]:-1
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 SetUnitBuff = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 SetTradePlayerItem = <function> defined =[C]:-1
 textRight1Font = "GameTooltipHeaderText"
 SetSendMailItem = <function> defined =[C]:-1
 ttSetBackdropLocked = true
 SetEnhancedConduit = <f`

**Comment by Dubwize** [comment] 2022-11-05 15:25
Still occurring with the new version.

Does not occur on button mouse over that are spells, or macros, professions, consumables, the special ability button or toys.

Does occur on button mouse over for mounts, and pets. 
Does occur on button click for everything else, also to note,  it fires the lua error twice each time. so once on mouse click, and once on mouse release.

`393x Interface/FrameXML/GameTooltip.lua:190: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: GameTooltip:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@Interface/FrameXML/GameTooltip.lua"]:190: in function <Interface/FrameXML/GameTooltip.lua:172>
[string "=[C]"]: in function `GameTooltip_SetDefaultAnchor'
[string "@Interface/AddOns/Bartender4/libs/LibActionButton-1.0-96/LibActionButton-1.0.lua"]:1455: in function `UpdateTooltip'
[string "@Interface/FrameXML/GameTooltip.lua"]:498: in function <Interface/FrameXML/GameTooltip.lua:485>
[string "=[C]"]: ?

Locals:
(*temporary) = GameTooltip {
 0 = <userdata>
 SetQuestPartyProgress = <function> defined =[C]:-1
 ttNumLines = 0
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 SetExistingSocketGem = <function> defined =[C]:-1
 SetHyperlink = <function> defined =[C]:-1
 SetUnit = <function> defined =[C]:-1
 SetAzeriteEssence = <function> defined =[C]:-1
 ttBackdropBorderColorApplied = false
 SetVoidWithdrawalItem = <function> defined =[C]:-1
 ttSetBackdropBorderColorLocked = true
 SetSocketGem = <function> defined =[C]:-1
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 Show = <function> defined =[C]:-1
 SetPetAction = <function> defined =[C]:-1
 SetEnhancedConduit = <function> defined =[C]:-1
 SetLFGDungeonReward = <function> defined =[C]:-1
 ttDefaultAnchored = false
 ApplyBackdrop = <function> defined @Interface/AddOns/TipTac/ttCore.lua:1636
 FadeOut = <function> defined @Interface/AddOns/TipTac/ttCore.lua:1449
 numMoneyFrames = 1
 BottomLeftCorner = Texture {
 }
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetQuestCurrency = <function> defined =[C]:-1
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 SetWeeklyReward = <function> defined =[C]:-1
 SetCurrencyTokenByID = <function> defined =[C]:-1
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 SetVoidDepositItem = <function> defined =[C]:-1
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 ttUnit = <table> {
 }
 comparing = false
 SetLootItem = <function> defined =[C]:-1
 ttIcon = Texture {
 }
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 NineSlice = Frame {
 }
 SetCompanionPet = <function> defined =[C]:-1
 TopEdge = Texture {
 }
 ttCount = FontString {
 }
 SetLootRollItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 ItemTooltip = Frame {
 }
 SetBagItem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined =[C]:-1
 BottomRightCorner = Texture {
 }
 SetBackdropColor = <function> defined @Interface/AddOns/TipTac/ttCore.lua:1652
 LeftEdge = Texture {
 }
 RightEdge = Texture {
 }
 TopRightCorner = Texture {
 }
 SetCurrencyByID = <function> defined =[C]:-1
 ttLastUpdate = 0
 ttSetIconTextureAndText = <function> defined @Interface/AddOns/TipTacItemRef/ttItemRef.lua:191
 hasMoney = 1
 SetSpellBookItem = <function> defined =[C]:-1
 ttBackdropColorApplied = false
 textLeft1Font = "GameTooltipHeaderText"
 SetInventoryItem = <function> defined =[C]:-1
 SetConduit = <function> defined =[C]:-1
 SetCurrencyToken = <function> defined =[C]:-1
 SetGuildBankItem = <function> defined =[C]:-1
 SetVoidItem = <function> defined =[C]:-1
 SetBackdropBorderColor = <function> defined @Interface/AddOns/TipTac/ttCore.lua:1660
 SetAction = <function> defined =[C]:-1
 Hide = <function> defined =[C]:-1
 ttDisplayingUnit = false
 waitingForData = false
 ttDisplayingAura = false
 textRight2Font = "GameTooltipText"
 BottomOverlay = Texture {
 }
 BottomEdge = Texture {
 }
 SetBackdrop = <function> defined @Interface/AddOns/TipTac/ttCore.lua:1644
 updateTooltipTimer = 0.200000
 TopOverlay = Texture {
 }
 GetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:347
 SetUnitDebuff = <function> defined =[C]:-1
 SetItemByID = <function> defined =[C]:-1
 TopLeftCorner = Texture {
 }
 SetQuestItem = <function> defined =[C]:-1
 ttAnchorType = "normal"
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
 SetToyByItemID = <function> defined =[C]:-1
 TextLeft1 = GameTooltipTextLeft1 {
 }
 TextRight1 = GameTooltipTextRight1 {
 }
 SetTrainerService = <function> defined =[C]:-1
 SetInboxItem = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 SetHeirloomByItemID = <function> defined =[C]:-1
 SetLFGDungeonShortageReward = <function> defined =[C]:-1
 backdropInfo = <table> {
 }
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 SetUnitBuff = <function> `

**Comment by Aur0r4** [comment] 2022-11-06 09:27
Have you guys tested the possible fix that frozn linked above?
https://github.com/frozn/TipTac/issues/77#issuecomment-1302511027

**Comment by Dubwize** [comment] 2022-11-07 00:09
Ok, i have deleted that local layout file and so far I'm not seeing the error come back.  Maybe this entry within the layout file a remnant from a old TT version ??

**Comment by Voxxel** [comment] 2022-11-07 00:39
I don't know what are you guys talking about but I use a goddamn heap of addons even in DF Beta and never encountered this kind of bug.

**Comment by frozn** [comment] 2022-11-14 00:24
@Dubwize: Good to hear, that your issue regarding SetPoint() is gone after the local layout file. 👍 

The issue with the blank tooltips is caused by other addons using a hidden scanning tooltip to determine informations about items/spells etc. and is a bug in the current wow patch 10.0.0. This will be fixed with the upcoming wow patch 10.0.2 (currently on PTR).

**Closed** 2022-11-14 00:26 UTC
Labels: 1_bug in other addon
