### ISSUE TITLE
[BUG] Error in 9.2 update.

### ISSUE THREAD

**Issue by hobulian** [frozn/TipTac#66] opened 2022-02-24 01:01 UTC
3x TipTacItemRef\ttItemRef.lua:1568: hooksecurefunc(): OnEnter is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@TipTacItemRef\ttItemRef.lua"]:1568: in function `?'
[string "@TipTacItemRef\ttItemRef.lua"]:209: in function <TipTacItemRef\ttItemRef.lua:209>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML\UIParent.lua"]:531: in function `UIParentLoadAddOn'
[string "@FrameXML\UIParent.lua"]:712: in function `PlayerChoice_LoadUI'
[string "@FrameXML\UIParent.lua"]:2229: in function <FrameXML\UIParent.lua:1324>

Locals:

Got error like this when entering world.

**Comment by frozn** [comment] 2022-02-24 08:31
Thanks for reporting this! But: Duplicate of #64. Already fixed with latest release yesterday. :sunglasses:

**Closed by frozn** 2022-02-24 08:31 UTC
Labels: bug, duplicate
