### ISSUE TITLE
Error without functionality #2

### ISSUE THREAD

**Issue by Zasz333** [frozn/TipTac#306] opened 2024-07-24 22:53 UTC
### Describe the bug

Updated to the latest version, not seeing any change to the tooltip but errors pop up. Tooltip remains default retail tooltip.

### Steps to Reproduce

No interaction happening.

### Expected behavior

I expect the addon to use my settings again.

### Additional context

389x TipTac/ttCore.lua:2814: attempt to call global 'GetMouseFocus' (a nil value)
[string "@TipTac/ttCore.lua"]:2814: in function `GetAnchorPosition'
[string "@TipTac/ttCore.lua"]:2940: in function `?'
[string "@TipTac/libs/LibFroznFunctions-1.0-25/LibFroznFunctions-1.0.lua"]:1175: in function `FireGroupEvent'
[string "@TipTac/ttCore.lua"]:1745: in function `SetCurrentDisplayParams'
[string "@TipTac/ttCore.lua"]:1631: in function <TipTac/ttCore.lua:1630>
[string "=[C]"]: in function `Show'
[string "@Altoholic/Services/Tooltip.lua"]:692: in function <Altoholic/Services/Tooltip.lua:690>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:290: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:238>
[string "=[C]"]: in function `securecallfunction'
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:235: in function `ProcessInfo'
[string "@Blizzard_GameTooltip/Mainline/GameTooltip.lua"]:929: in function `SetWorldCursor'
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:1366: in function <...rfaceBlizzard_UIParent/Mainline/UIParent.lua:1289>
[string "=[C]"]: ?

Locals:
self = TipTac {
 RightEdge = Texture {
 }
 TopEdge = Texture {
 }
 BottomRightCorner = Texture {
 }
 LeftEdge = Texture {
 }
 BottomEdge = Texture {
 }
 BottomLeftCorner = Texture {
 }
 text = FontString {
 }
 close = Button {
 }
 TopLeftCorner = Texture {
 }
 Center = Texture {
 }
 backdropInfo = <table> {
 }
 TopRightCorner = Texture {
 }
}
tip = GameTooltip {
 ItemTooltip = Frame {
 }
 BottomOverlay = Texture {
 }
 NineSlice = Frame {
 }
 TopEdge = Texture {
 }
 LeftEdge = Texture {
 }
 textLeft1Font = "GameTooltipHeaderText"
 textRight2Font = "GameTooltipText"
 TopOverlay = Texture {
 }
 TextLeft1 = GameTooltipTextLeft1 {
 }
 StatusBar = GameTooltipStatusBar {
 }
 processingInfo = <table> {
 }
 infoList = <table> {
 }
 supportsDataRefresh = true
 Center = Texture {
 }
 RightEdge = Texture {
 }
 BottomEdge = Texture {
 }
 BottomRightCorner = Texture {
 }
 BottomLeftCorner = Texture {
 }
 TopRightCorner = Texture {
 }
 TopLeftCorner = Texture {
 }
 backdropInfo = <table> {
 }
 updateTooltipTimer = 0.200000
 textRight1Font = "GameTooltipHeaderText"
 shoppingTooltips = <table> {
 }
 TextRight1 = GameTooltipTextRight1 {
 }
 supportsItemComparison = true
 textLeft2Font = "GameTooltipText"
 TextRight2 = GameTooltipTextRight2 {
 }
 TextLeft2 = GameTooltipTextLeft2 {
 }
}
frameParams = <table> {
 config = <table> {
 }
 currentDisplayParams = <table> {
 }
 frameName = "GameTooltip"
}
isUnit = nil
(*temporary) = nil
(*temporary) = "attempt to call global 'GetMouseFocus' (a nil value)"
TT_CacheForFrames = <table> {
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
}
TT_TIP_CONTENT = <table> {
 unknownOnCleared = 8
 spell = 3
 item = 4
 aura = 2
 unknownOnShow = 7
 others = 6
 action = 5
 unit = 1
}
cfg = <table> {
 colorReactText6 = <table> {
 }
 hideSpecializationAndClassText = true
 classification_elite = "%s Elite"
 tipBackdropEdge = "nil"
 showMount = false
 backdropEdgeSize = 16
 showMountCollected = false
 showMountText = false
 hideFactionText = true
 powerBar = true
 anchorFrameUnitPoint = "BOTTOM"
 showAuraCooldown = false
 colorSameGuild = <table> {
 }
 tipBorderColor = <table> {
 }
 noCooldownCount = true
 t_showTalentText = false
 colorReactText5 = <table> {
 }
 classification_rare = "%s|r (Rare)"
 enableChatHoverTips = true
 colorGuildByReaction = false
 barsCondenseValues = true
 left = 610.999904
 if_showKeystoneTimeLimit = false
 colorGuild = <table> {
 }
 reactColoredBackdrop = false
 guildRankFormat = "title"
 classification_trivial = "%s "
 iconSize = 25
 colorReactText9 = <table> {
 }
 colorRace = <table> {
 }
 minimapConfig = <table> {
 }
 targetYouText = "<< YOU >>"
 manaBar = true
 gradientColor = <table> {
 }
 hidePvpText = true
 pixelPerfectBackdrop = false
 fadeTime = 0
 if_showKeystoneRewardLevel = false
 showGuildRank = true
 top = 368.000055
 talentOnlyInParty = false
 gradientTip = false
 if_modifyAchievementTips = false
 reactColoredText = false
 if_showItemId = false
 colorReactText8 = <table> {
 }
 t_enable = false
 t_showTalents = false
 gttScale = 1.200000
 showCurrentUnitSpeed = false
 classification_rareelite = "+%s|r (Rare Elite)"
 t_showTalentIcon = false
 iconFaction = true
 overrideFade = true
 if_enable = false
 preFadeTime = 0
 optionsLeft = 9.000010
 reactIcon = false
 if_showSpellIdAndRank = false
 showTarget = "belowNameRealm"
 barTexture = "Interface\AddOns\Empath-Textures\textures\Empath12"
 talentCacheSize = 5
 enableBackdrop = true
 tipColor = <table> {
 }
 showMinimapIcon = false
 colRace = "|cffffffff"
 healthBarText = "value"
 if_modifyKeystoneTips = false
 colorReactText7 = <table> {
 }
 classification_normal = "%s "
 if_showAuraCaster = false
 backdropInsets = 4
 classification_minus = "%s "
 anchorFrameTipType = "mouse"
 reactColoredBorde

### Version of TipTac Reborn

24.07.24

### Flavor/Version of WoW

Retail

**Comment by frozn** [comment] 2024-07-25 00:49
Thanks for reporting this! 👍

Fixed with the latest release [v24.07.25](https://github.com/frozn/TipTac/releases/tag/v24.07.25-release).

Duplicate of https://github.com/frozn/TipTac/issues/301.

**Closed** 2024-07-25 00:50 UTC
Labels: 1_bug, 3_duplicate
