### ISSUE TITLE
Tooltip for Plater aura frames

### ISSUE THREAD

**Issue by hobulian** [frozn/TipTac#23] opened 2022-01-15 17:27 UTC
Now tiptac seems not supporting plater nameplates aura tooltip. I tried to apply your WorldquestTracker tooltip hook but keep failing. It's frame is like this now.
https://imgur.com/a/ORyZMKq

You can test aura tooltip by enter "/plater" in chat and check [show tooltip] in at BUFF SETTINGS
https://imgur.com/a/xu80ALs

It's tooltip lua is at
https://github.com/Tercioo/Plater-Nameplates/blob/master/Plater_Auras.lua

**Comment by frozn** [comment] 2022-01-18 17:11
I added the styling of auras from standard nameplate and addon Plater and committed my changes to main-branch.

**Comment by frozn** [comment] 2022-01-18 21:23
Added additional changes due to regression. Now all seems fine.

**Comment by hobulian** [comment] 2022-01-19 02:15
It seems fine to me. :)

**Closed** 2022-01-19 06:40 UTC
