### ISSUE TITLE
[Flickering] Problem with  World Quest Tracker embedded tooltips

### ISSUE THREAD

**Issue by hobulian** [frozn/TipTac#7] opened 2021-12-24 14:53 UTC
Always Thanks for your hard work!

 

Seems to got problem after last update. I am using World Quest Tracker addon.

https://www.curseforge.com/wow/addons/world-quest-tracker

 

and It seems than when there's embedded item or artifact power in toolltip it goes broken like pic below.

https://imgur.com/a/2hkXLo9

 

wasn't happened before but after last update it broken like this.

 

tip:SetPadding(tipBackdrop.insets.right, tipBackdrop.insets.bottom, tipBackdrop.insets.left, tipBackdrop.insets.top);

 

this line in function tt:ApplyTipBackdrop(tip) causes the problem.

**Comment by hobulian** [comment] 2021-12-29 18:12
I added "--" to tip:SetPadding(tipBackdrop.insets.right, tipBackdrop.insets.bottom, tipBackdrop.insets.left, tipBackdrop.insets.top);
so it's now adequately functioning except war-mode bonused azerite worldquests. it's still flickering.

**Comment by k1ck3r** [comment] 2021-12-30 15:59
having same issue, but on my end, it only widens - https://imgur.com/vn3unYT
anyhow seems there is a way, but prefer to wait for Frozn's version ;)

**Comment by k1ck3r** [comment] 2021-12-31 10:57
@hobulian do you have any issues when hovering over GarrisonUI?

**Comment by hobulian** [comment] 2022-01-01 13:35
@k1ck3r hmm GarrisonUI

> @hobulian do you have any issues when hovering over GarrisonUI?

Which part of GarrisonUI?

**Comment by hobulian** [comment] 2022-01-01 14:17
Should add

local function GTT_AddQuestRewardsToTooltip(self,id,style)
	-- "ttDisplayingAura" will flag the tooltip is currently showing an quest
	self.ttDisplayingQuest = true;	
			
	gtt_anchorType, gtt_anchorPoint = GetAnchorPosition(self);

	if (gtt_anchorType == "mouse") then
		local gttAnchor = self:GetAnchorType();
		if (gttAnchor ~= "ANCHOR_NONE") then
			-- Since TipTac handles all the anchoring, we want to use "ANCHOR_NONE" here
			self:SetAnchorType("ANCHOR_NONE");
		end
		tt:AnchorFrameToMouse(self);
	end
end

-- 제조법들은 배경이 중복해서 표현되는 문제가 있음
local function STT_SetBackdropStyle(self, style, embedded)
	local _, link = self:GetItem();
	if (link) then
		local _, id = link:match("H?(%a+):(%d+)");
		if (id) then
			local itemType = select(12,GetItemInfo(link));
			if itemType == 9 then
				self.NineSlice:SetCenterColor(0, 0, 0);
				self.NineSlice:Hide();
			end
		end
	end
end



and

hooksecurefunc("GameTooltip_AddQuestRewardsToTooltip", GTT_AddQuestRewardsToTooltip);
hooksecurefunc("SharedTooltip_SetBackdropStyle", STT_SetBackdropStyle);

to 

function tt:HookTips()

**Comment by frozn** [comment] 2022-01-03 14:53
issue with embedded tooltips fixed with [v22.01.03](https://github.com/frozn/TipTac/releases/tag/v22.01.03).

@k1ck3r: Can't reproduce your problems with GarrisonUI of shadowland. Perhaps you can make another small video of this to show it?

**Comment by hobulian** [comment] 2022-01-10 13:39
Azerite reward keeps flickering even now

**Comment by k1ck3r** [comment] 2022-01-13 15:30
Hey guys,

stopping by to leave my feedback regarding the "flickering" when hovering on some UI elements of other addon. Seems that all that flickering is related to the anchor point of your cursor's tooltip.

Previously was using all tooltips to be on "Top Left" of the mouse anchor with changes to the X and Y. So, once you set "Bottom Right" most of not all flickering is gone. 

I know that latest push from @frozn fixes 99% of the things (will open different issue, with all info i got) related to TipTac and we really love him for this :D but if you are still having issue with some other addons (wardrobe enhances, venture plan for missions, world quest tracker) the issue is with the other addon for sure.

Anyhow going to my new topic now ;)

**Comment by hobulian** [comment] 2022-01-28 16:02
No more flickering after updated today!

**Comment by frozn** [comment] 2022-01-28 21:34
An unexpected miracle! :sweat_smile:

**Comment by frozn** [comment] 2023-01-23 22:50
Should also be finally solved with latest release [v23.01.23](https://github.com/frozn/TipTac/releases/tag/v23.01.23-release).

**Closed** 2023-03-07 22:38 UTC
Labels: 1_bug, 2_to develop, 3_solved
