### ISSUE TITLE
Lua error TipTacItemRef

### ISSUE THREAD

**Issue by Sayangjoy** [frozn/TipTac#333] opened 2024-08-15 10:24 UTC
### Describe the bug

When i load the game and kill a mob, i loot the items, then i get this LUA error: 

Message: ...nterface/AddOns/TipTacItemRef/libs/LibItemString.lua:321: attempt to call field 'SurfaceArgs' (a nil value)
Time: Thu Aug 15 12:17:34 2024
Count: 5
Stack: ...nterface/AddOns/TipTacItemRef/libs/LibItemString.lua:321: attempt to call field 'SurfaceArgs' (a nil value)
[string "@Interface/AddOns/TipTacItemRef/libs/LibItemString.lua"]:321: in function <...nterface/AddOns/TipTacItemRef/libs/LibItemString.lua:316>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/TipTacItemRef/ttItemRef.lua"]:2417: in function `item'
[string "@Interface/AddOns/TipTacItemRef/ttItemRef.lua"]:1282: in function <Interface/AddOns/TipTacItemRef/ttItemRef.lua:1271>
[string "@Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua"]:389: in function <...libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:387>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:61: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:56>
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:81: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:77>
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:117: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:107>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:142: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:135>
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:288: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:238>
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:235: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:234>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `SetBagItem'
[string "@Interface/AddOns/Blizzard_UIPanels_Game/Mainline/ContainerFrame.lua"]:1533: in function `OnUpdate'
[string "@Interface/AddOns/Blizzard_UIPanels_Game/Mainline/ContainerFrame.lua"]:1492: in function `OnEnter'
[string "@Interface/AddOns/Blizzard_UIPanels_Game/Mainline/ContainerFrame.lua"]:1488: in function <...s/Blizzard_UIPanels_Game/Mainline/ContainerFrame.lua:1487>
[string "=[C]"]: ?

Locals: self = <table> {
 ITEM_LEVEL_PATTERN = "Item Level (%d+)"
 ITEMSTRING_PROPERTY_INDEX = <table> {
 }
 TIMEWARPED_LEVEL_ADJUST = <table> {
 }
 UPGRADED_LEVEL_ADJUST = <table> {
 }
 ITEMSTRING_PATTERN = "(item:[^|]+)"
 ScanTip = LibItemStringScanTip {
 }
 TOOLTIP_MAXLINE_LEVEL = 5
 REVISION = 4
 TIMEWARPED_WARFORGED_LEVEL_ADJUST = <table> {
 }
}
itemLink = "[Hearthstone]"
tooltipData = <table> {
 dataInstanceID = 18332
 type = 0
 isAzeriteEmpoweredItem = false
 isAzeriteItem = false
 id = 6948
 hyperlink = "[Hearthstone]"
 isCorruptedItem = false
 lines = <table> {
 }
}
(*temporary) = nil
(*temporary) = <table> {
 dataInstanceID = 18332
 type = 0
 isAzeriteEmpoweredItem = false
 isAzeriteItem = false
 id = 6948
 hyperlink = "[Hearthstone]"
 isCorruptedItem = false
 lines = <table> {
 }
}
(*temporary) = "attempt to call field 'SurfaceArgs' (a nil value)"
LIS = <table> {
 ITEM_LEVEL_PATTERN = "Item Level (%d+)"
 ITEMSTRING_PROPERTY_INDEX = <table> {
 }
 TIMEWARPED_LEVEL_ADJUST = <table> {
 }
 UPGRADED_LEVEL_ADJUST = <table> {
 }
 ITEMSTRING_PATTERN = "(item:[^|]+)"
 ScanTip = LibItemStringScanTip {
 }
 TOOLTIP_MAXLINE_LEVEL = 5
 REVISION = 4
 TIMEWARPED_WARFORGED_LEVEL_ADJUST = <table> {
 }
}

### Steps to Reproduce

1. load game with tiptac addon and tiptacitemref addon.
2. kill a mob ingame
3. loot the items
4. the lua error pops-up

### Version of TipTac Reborn

Latest 15-08-2024

Tiptac: 24.08.05
WoW: 11.0.2

### Flavor/Version of WoW

WoW v 11.0.2  Prepatch  TWW

**Comment by Nyuwb** [comment] 2024-08-15 13:58
Same here :

```Message: ...nterface/AddOns/TipTacItemRef/libs/LibItemString.lua:321: attempt to call field 'SurfaceArgs' (a nil value)
Time: Thu Aug 15 15:50:39 2024
Count: 1
Stack: ...nterface/AddOns/TipTacItemRef/libs/LibItemString.lua:321: attempt to call field 'SurfaceArgs' (a nil value)
[string "@Interface/AddOns/TipTacItemRef/libs/LibItemString.lua"]:321: in function <...nterface/AddOns/TipTacItemRef/libs/LibItemString.lua:316>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/TipTacItemRef/ttItemRef.lua"]:2417: in function `item'
[string "@Interface/AddOns/TipTacItemRef/ttItemRef.lua"]:1282: in function <Interface/AddOns/TipTacItemRef/ttItemRef.lua:1271>
[string "@Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua"]:389: in function <...libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:387>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:61: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:56>
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:81: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:77>
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:117: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:107>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:142: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:135>
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:288: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:238>
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:235: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:234>
[string "=[C]"]: in function `ProcessInfo'
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipComparisonManager.lua"]:251: in function `SetItemTooltip'
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipComparisonManager.lua"]:169: in function `RefreshItems'
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipComparisonManager.lua"]:160: in function `CompareItem'
[string "@Interface/AddOns/Blizzard_GameTooltip/Mainline/GameTooltip.lua"]:450: in function <...AddOns/Blizzard_GameTooltip/Mainline/GameTooltip.lua:446>
[string "=[C]"]: in function `GameTooltip_ShowCompareItem'
[string "@Interface/AddOns/Blizzard_UIPanels_Game/Mainline/MerchantFrame.lua"]:685: in function `MerchantItemButton_OnEnter'
[string "*MerchantFrame.xml:46_OnEnter"]:1: in function <[string "*MerchantFrame.xml:46_OnEnter"]:1>

Locals: self = <table> {
 ITEM_LEVEL_PATTERN = "Niveau d'objet (%d+)"
 ITEMSTRING_PROPERTY_INDEX = <table> {
 }
 TIMEWARPED_LEVEL_ADJUST = <table> {
 }
 UPGRADED_LEVEL_ADJUST = <table> {
 }
 ITEMSTRING_PATTERN = "(item:[^|]+)"
 ScanTip = LibItemStringScanTip {
 }
 TOOLTIP_MAXLINE_LEVEL = 5
 REVISION = 4
 TIMEWARPED_WARFORGED_LEVEL_ADJUST = <table> {
 }
}
itemLink = "[Croquenots de défense de Dalaran]"
tooltipData = <table> {
 dataInstanceID = 14232
 type = 0
 isAzeriteEmpoweredItem = false
 isAzeriteItem = false
 id = 218071
 hyperlink = "[Croquenots de défense de Dalaran]"
 isCorruptedItem = false
 lines = <table> {
 }
}
(*temporary) = nil
(*temporary) = <table> {
 dataInstanceID = 14232
 type = 0
 isAzeriteEmpoweredItem = false
 isAzeriteItem = false
 id = 218071
 hyperlink = "[Croquenots de défense de Dalaran]"
 isCorruptedItem = false
 lines = <table> {
 }
}
(*temporary) = "attempt to call field 'SurfaceArgs' (a nil value)"
LIS = <table> {
 ITEM_LEVEL_PATTERN = "Niveau d'objet (%d+)"
 ITEMSTRING_PROPERTY_INDEX = <table> {
 }
 TIMEWARPED_LEVEL_ADJUST = <table> {
 }
 UPGRADED_LEVEL_ADJUST = <table> {
 }
 ITEMSTRING_PATTERN = "(item:[^|]+)"
 ScanTip = LibItemStringSca```

**Comment by frozn** [comment] 2024-08-19 00:12
Thanks for reporting this! 👍

Calling `TooltipUtil.SurfaceArgs()` is obsolete (since df 10.1.0) and can be removed. The fix will be included in the next release.

Duplicate of #330.

**Closed** 2024-08-19 00:12 UTC
Labels: 1_bug, 3_duplicate
