### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by DaleHuntGB** [frozn/TipTac#89] opened 2022-08-19 20:01 UTC
Hi there,

Got this error when hovering over the reward within the Quest Log from the Timewalking Event.
```
1x TipTacItemRef\ttItemRef.lua:683: Usage: GetItemInfo(itemID|"name"|"itemlink")
[string "=[C]"]: in function `GetItemInfo'
[string "@TipTacItemRef\ttItemRef.lua"]:683: in function <TipTacItemRef\ttItemRef.lua:670>
[string "=[C]"]: ?
[string "=[C]"]: in function `SetQuestLogItem'
[string "@FrameXML\QuestInfo.lua"]:1070: in function <FrameXML\QuestInfo.lua:1059>

Locals:
(*temporary) = nil
```
Hope this helps. Also - not running any sort of custom Quest Log, just Blizzard default.

**Comment by frozn** [comment] 2022-08-19 21:41
Do you mean this quest?

https://www.wowhead.com/quest=64709/a-fel-path-through-time

Item:
https://www.wowhead.com/item=192437/cache-of-fated-treasures

**Comment by DaleHuntGB** [comment] 2022-08-19 21:53
That's the one.

**Comment by frozn** [comment] 2022-08-19 22:34
Then we have a problem: I can't reproduce this error. I didn't get this error if hovering over the mentioned quest item in my quest log... 🤔

**Comment by DaleHuntGB** [comment] 2022-08-20 07:11
Hm.. weird - maybe it was just a weird conflict in my UI but as I said, no other AddOns are being used for the tooltip or the Quest Log.

**Comment by frozn** [comment] 2022-09-03 11:03
I suggest that we close this issue. If it happens again, we will open it again.

**Closed by frozn** 2022-09-03 11:03 UTC
Labels: unclear if bug or no bug
