### ISSUE TITLE
Itemref/libs/libitemstring

### ISSUE THREAD

**Issue by Faulkal** [frozn/TipTac#331] opened 2024-08-14 02:13 UTC
### Describe the bug

Pretty sure i get this lua error when hovering over things, though im not sure what. 

### Steps to Reproduce

not really sure

### Additional context

3004x TipTacItemRef/libs/LibItemString.lua:321: attempt to call field 'SurfaceArgs' (a nil value)
[string "@TipTacItemRef/libs/LibItemString.lua"]:321: in function <TipTacItemRef/libs/LibItemString.lua:316>
[string "=(tail call)"]: ?
[string "@TipTacItemRef/ttItemRef.lua"]:2417: in function `item'
[string "@TipTacItemRef/ttItemRef.lua"]:1282: in function <TipTacItemRef/ttItemRef.lua:1271>
[string "@TipTac/libs/LibFroznFunctions-1.0-29/LibFroznFunctions-1.0.lua"]:389: in function <...libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:387>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:61: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:56>
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:81: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:77>
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:117: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:107>
[string "=[C]"]: in function `SetAttribute'
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:142: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:135>
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:288: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:238>
[string "=[C]"]: in function `securecallfunction'
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:235: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:234>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetAction'
[string "@Bartender4/libs/LibActionButton-1.0-117/LibActionButton-1.0.lua"]:2278: in function `SetTooltip'
[string "@Bartender4/libs/LibActionButton-1.0-117/LibActionButton-1.0.lua"]:1985: in function <...er4/libs/LibActionButton-1.0/LibActionButton-1.0.lua:1978>
[string "@Bartender4/libs/LibActionButton-1.0-117/LibActionButton-1.0.lua"]:1060: in function <...er4/libs/LibActionButton-1.0/LibActionButton-1.0.lua:1058>

Locals:
self = <table> {
 ITEM_LEVEL_PATTERN = "Item Level (%d+)"
 ITEMSTRING_PROPERTY_INDEX = <table> {
 }
 TIMEWARPED_LEVEL_ADJUST = <table> {
 }
 UPGRADED_LEVEL_ADJUST = <table> {
 }
 ITEMSTRING_PATTERN = "(item:[^|]+)"
 ScanTip = LibItemStringScanTip {
 }
 TOOLTIP_MAXLINE_LEVEL = 5
 REVISION = 4
 TIMEWARPED_WARFORGED_LEVEL_ADJUST = <table> {
 }
}
itemLink = "|cffffffff|Hitem:109076::::::::70:70:::::::::|h[Goblin Glider Kit]|h|r"
tooltipData = <table> {
 dataInstanceID = 102
 type = 0
 isAzeriteEmpoweredItem = false
 isAzeriteItem = false
 id = 109076
 hyperlink = "|cffffffff|Hitem:109076::::::::70:70:::::::::|h[Goblin Glider Kit]|h|r"
 isCorruptedItem = false
 lines = <table> {
 }
}
(*temporary) = nil
(*temporary) = <table> {
 dataInstanceID = 102
 type = 0
 isAzeriteEmpoweredItem = false
 isAzeriteItem = false
 id = 109076
 hyperlink = "|cffffffff|Hitem:109076::::::::70:70:::::::::|h[Goblin Glider Kit]|h|r"
 isCorruptedItem = false
 lines = <table> {
 }
}
(*temporary) = "attempt to call field 'SurfaceArgs' (a nil value)"
LIS = <table> {
 ITEM_LEVEL_PATTERN = "Item Level (%d+)"
 ITEMSTRING_PROPERTY_INDEX = <table> {
 }
 TIMEWARPED_LEVEL_ADJUST = <table> {
 }
 UPGRADED_LEVEL_ADJUST = <table> {
 }
 ITEMSTRING_PATTERN = "(item:[^|]+)"
 ScanTip = LibItemStringScanTip {
 }
 TOOLTIP_MAXLINE_LEVEL = 5
 REVISION = 4
 TIMEWARPED_WARFORGED_LEVEL_ADJUST = <table> {
 }
}

### Version of TipTac Reborn

24.08.05

### Flavor/Version of WoW

retail 11.0.2

**Comment by fraerie** [comment] 2024-08-14 02:46
Getting this error when mousing over inventory items

956x TipTacItemRef/libs/LibItemString.lua:321: attempt to call field 'SurfaceArgs' (a nil value)
[string "@TipTacItemRef/libs/LibItemString.lua"]:321: in function <TipTacItemRef/libs/LibItemString.lua:316>
[string "=(tail call)"]: ?
[string "@TipTacItemRef/ttItemRef.lua"]:2417: in function `item'
[string "@TipTacItemRef/ttItemRef.lua"]:1282: in function <TipTacItemRef/ttItemRef.lua:1271>
[string "@TipTac/libs/LibFroznFunctions-1.0-29/LibFroznFunctions-1.0.lua"]:389: in function <...libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:387>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:61: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:56>
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:81: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:77>
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:117: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:107>
[string "=[C]"]: in function `SetAttribute'
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:142: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:135>
...
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetHyperlink'
[string "@ArkInventory/Core/ArkInventoryTooltip.lua"]:284: in function <...aceArkInventory/Core/ArkInventoryTooltip.lua:237>
[string "@ArkInventory/Core/ArkInventoryTooltip.lua"]:557: in function <...aceArkInventory/Core/ArkInventoryTooltip.lua:417>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@ArkInventory/Core/ArkInventory.lua"]:9199: in function `Frame_Item_UpdateTooltip'
[string "@ArkInventory/Core/ArkInventory.lua"]:9325: in function `Frame_Item_OnEnter'
[string "*ArkInventory.xml:353_OnEnter"]:1: in function <[string "*ArkInventory.xml:353_OnEnter"]:1>

Locals:
self = <table> {
 ITEM_LEVEL_PATTERN = "Item Level (%d+)"
 ITEMSTRING_PROPERTY_INDEX = <table> {
 }
 TIMEWARPED_LEVEL_ADJUST = <table> {
 }
 UPGRADED_LEVEL_ADJUST = <table> {
 }
 ITEMSTRING_PATTERN = "(item:[^|]+)"
 ScanTip = LibItemStringScanTip {
 }
 TOOLTIP_MAXLINE_LEVEL = 5
 REVISION = 4
 TIMEWARPED_WARFORGED_LEVEL_ADJUST = <table> {
 }
}
itemLink = "|cff1eff00|Hitem:79255::::::::70:102:::::::::|h[Starlight Ink]|h|r"
tooltipData = <table> {
 dataInstanceID = 35096
 type = 0
 isAzeriteEmpoweredItem = false
 isAzeriteItem = false
 id = 79255
 hyperlink = "|cff1eff00|Hitem:79255::::::::70:102:::::::::|h[Starlight Ink]|h|r"
 isCorruptedItem = false
 lines = <table> {
 }
}
(*temporary) = nil
(*temporary) = <table> {
 dataInstanceID = 35096
 type = 0
 isAzeriteEmpoweredItem = false
 isAzeriteItem = false
 id = 79255
 hyperlink = "|cff1eff00|Hitem:79255::::::::70:102:::::::::|h[Starlight Ink]|h|r"
 isCorruptedItem = false
 lines = <table> {
 }
}
(*temporary) = "attempt to call field 'SurfaceArgs' (a nil value)"
LIS = <table> {
 ITEM_LEVEL_PATTERN = "Item Level (%d+)"
 ITEMSTRING_PROPERTY_INDEX = <table> {
 }
 TIMEWARPED_LEVEL_ADJUST = <table> {
 }
 UPGRADED_LEVEL_ADJUST = <table> {
 }
 ITEMSTRING_PATTERN = "(item:[^|]+)"
 ScanTip = LibItemStringScanTip {
 }
 TOOLTIP_MAXLINE_LEVEL = 5
 REVISION = 4
 TIMEWARPED_WARFORGED_LEVEL_ADJUST = <table> {
 }
}

**Comment by frozn** [comment] 2024-08-19 00:11
Thanks for reporting this! 👍

Calling `TooltipUtil.SurfaceArgs()` is obsolete (since df 10.1.0) and can be removed. The fix will be included in the next release.

Duplicate of #330.

**Closed** 2024-08-19 00:11 UTC
Labels: 1_bug, 3_duplicate
