### ISSUE TITLE
Error with v22.06.02 on Retail

### ISSUE THREAD

**Issue by wheatbread** [frozn/TipTac#83] opened 2022-06-03 00:42 UTC
Hi, thank you for the updates!

I'm getting the following error with the latest release on retail v22.06.02:

```
825x Usage: local sources = C_TransmogCollection.GetAppearanceSources(appearanceID, categoryType, transmogLocation)
[string "=[C]"]: in function `GetAppearanceSources'
[string "@FrameXML\CollectionsUtil.lua"]:76: in function `GetSortedAppearanceSources'
[string "@TipTacItemRef\ttItemRef.lua"]:1290: in function <TipTacItemRef\ttItemRef.lua:1285>
[string "=[C]"]: in function `RefreshAppearanceTooltip'
[string "@Blizzard_Collections\Blizzard_Wardrobe.lua"]:2272: in function `SetAppearanceTooltip'
[string "@Blizzard_Collections\Blizzard_Wardrobe.lua"]:2460: in function <...ceBlizzard_Collections\Blizzard_Wardrobe.lua:2436>
[string "=[C]"]: ?

Locals:
(*temporary) = "Usage: local sources = C_TransmogCollection.GetAppearanceSources(appearanceID, categoryType, transmogLocation)"
```

I also tried completely deleting tiptac from my Addon folder before adding the new one, but it still did not fix the errors.

**Comment by frozn** [comment] 2022-06-03 07:09
In which situations do you get this errors?

Possible duplicate of #82.

**Closed** 2022-08-10 21:18 UTC
Labels: bug, duplicate
