### ISSUE TITLE
[Bug] LFG dropdown menu backdrop overlapped with elv(and border overlapped with windtool's shadow)

### ISSUE THREAD

**Issue by hobulian** [frozn/TipTac#55] opened 2022-02-11 13:03 UTC
problem with LFG finder dropdown menu when if you using ELV ui

also sometimes, Tiptac's dropdown menu border overlapped with elv windtool's border even i modified windtool with #45's recommendation.

https://imgur.com/a/uGEdHbG

**Comment by frozn** [comment] 2022-02-11 19:24
Can't reproduce it with ElvUI and Windtool:

![image](https://user-images.githubusercontent.com/5655881/153656079-890317db-c587-49ad-ae2a-14bdf6c38c3c.png)

I changed/increased the shadow color to see it better. But everything's looking fine. :thinking:

**Comment by hobulian** [comment] 2022-02-12 02:40
If your backdrop color alpha is about < 0.8 you can see dark rectangular shapes inside dropdown menu.

https://imgur.com/a/WgU1RG7

I enlarged SC that i uploaded. When your tip's backdrop alpha is low you can see inner rectangle shaped dark area.

about border, it's same . low alpha backdrop + white colored alpha 1pixel (255,255,255,100) can reproduce problem. If not, reloading game few times then it can be reproduced.

**Comment by frozn** [comment] 2022-02-13 22:42
I have revised the handling of backdrops for DropDownList1/2. The issue with the overlapping dark area is solved and I committed my changes to main branch.

How about it?

**Comment by hobulian** [comment] 2022-02-14 02:02
No more dark area found.
But found #45 's windtool problem again. So i modified windtool's lua

```shadow:SetFrameLevel(shadowFrameLevel)
    if frame:GetName() and string.find(frame:GetName(), "DropDownList") then
		shadow:SetFrameStrata("LOW")
    else
		shadow:SetFrameStrata(frame:GetFrameStrata())
    end
```

**Comment by hobulian** [comment] 2022-02-14 09:37
Yeah if i modify windtools framestrata, overlapping border problem is gone. But hope you check tiptac once with that problem without modifying windtool this can be solved

**Comment by frozn** [comment] 2022-02-14 11:02
I think it's definitively wrong in WindTools that it sets the same frame strata/level like the tooltip. To manipulate the shadow frame from TipTac's side doesn't look right to me.

**Comment by hobulian** [comment] 2022-02-14 13:52
Find with that. I will request this to Windtool's author. :)

**Closed** 2022-02-14 14:33 UTC
Labels: bug, to develop
