### ISSUE TITLE
WoW wotlk PTR server issues, just a heads up

### ISSUE THREAD

**Issue by wazerstar** [frozn/TipTac#233] opened 2023-05-19 18:21 UTC
From bugsack on PTR WOTLK server

```
14x TipTacItemRef/ttItemRef.lua:1729: hooksecurefunc(): EmbeddedItemTooltip_SetSpellByQuestReward is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@TipTacItemRef/ttItemRef.lua"]:1729: in function `ApplyHooksToTips'
[string "@TipTacItemRef/ttItemRef.lua"]:1835: in function `HookTips'
[string "@TipTacItemRef/ttItemRef.lua"]:389: in function `?'
[string "@TipTacItemRef/ttItemRef.lua"]:340: in function <TipTacItemRef/ttItemRef.lua:340>

Locals:
```

**Comment by frozn** [comment] 2023-05-19 20:24
Thanks for reporting this! 👍 

But because it's a duplicate of #228, I close this one for a better overview.

**Closed by frozn** 2023-05-19 20:24 UTC
Labels: 3_duplicate, 1_bug in wow
