### ISSUE TITLE
Lua Error Mousing Over Quest Currency Reward

### ISSUE THREAD

**Issue by Rebel-Kat** [frozn/TipTac#321] opened 2024-07-30 00:37 UTC
### Describe the bug

Opening a quest and mousing over Mark of the World Tree for Hyjal 2 errors come up. Not sure about other currencies, I just came over to redo this questline.

### Steps to Reproduce

Close error and mouse over currency earned for quest, in this case again Mark of the World Tree, I circled in red the item I mouse over to get this to happen

![Screenshot 2024-07-29 193318](https://github.com/user-attachments/assets/a5513d3d-3336-4f59-8303-da9e9f921fbd)

### Expected behavior

None

### Additional context

First Lua error

Message: Interface/AddOns/TipTacItemRef/ttItemRef.lua:921: attempt to call global 'GetQuestCurrencyInfo' (a nil value)
Time: Mon Jul 29 19:29:56 2024
Count: 3
Stack: Interface/AddOns/TipTacItemRef/ttItemRef.lua:921: attempt to call global 'GetQuestCurrencyInfo' (a nil value)
[string "=[C]"]: in function `GetQuestCurrencyInfo'
[string "@Interface/AddOns/TipTacItemRef/ttItemRef.lua"]:921: in function <Interface/AddOns/TipTacItemRef/ttItemRef.lua:918>
[string "=[C]"]: in function `SetQuestCurrency'
[string "@Interface/AddOns/Blizzard_UIPanels_Game/Mainline/QuestInfo.lua"]:1250: in function <...AddOns/Blizzard_UIPanels_Game/Mainline/QuestInfo.lua:1229>

Locals: 

Second error 

Message: Interface/AddOns/TipTacItemRef/ttItemRef.lua:921: attempt to call global 'GetQuestCurrencyInfo' (a nil value)
Time: Mon Jul 29 19:32:42 2024
Count: 6
Stack: Interface/AddOns/TipTacItemRef/ttItemRef.lua:921: attempt to call global 'GetQuestCurrencyInfo' (a nil value)
[string "=[C]"]: in function `GetQuestCurrencyInfo'
[string "@Interface/AddOns/TipTacItemRef/ttItemRef.lua"]:921: in function <Interface/AddOns/TipTacItemRef/ttItemRef.lua:918>
[string "=[C]"]: in function `SetQuestCurrency'
[string "@Interface/AddOns/Blizzard_UIPanels_Game/Mainline/QuestInfo.lua"]:1250: in function `UpdateTooltip'
[string "@Interface/AddOns/Blizzard_GameTooltip/Mainline/GameTooltip.lua"]:421: in function <...AddOns/Blizzard_GameTooltip/Mainline/GameTooltip.lua:414>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?

Locals: 

### Version of TipTac Reborn

v24.07.28-release

### Flavor/Version of WoW

Retail

**Comment by frozn** [comment] 2024-07-30 09:15
Thanks for reporting this! 👍

Will be fixed with the next release. Duplicate of #319.

**Comment by Rebel-Kat** [comment] 2024-07-30 15:51
OOF,  sorry for creating a duplicate post, will keep a sharper eye and post with them
Or is it better to make separate posts

**Comment by frozn** [comment] 2024-07-31 18:12
It's good to check if the latest issues already mention the error you encounter. If it's the exact same lua error, then it's normally not necessary to post something additionally, because I'm already on it. If the error is different but belongs to one of the latest issues, then it's good to post your infos there. If it's something new, a new issue needs to be created.

Nevertheless it's good to report problems or feature request, so that I can improve this addon. 😉

**Closed** 2024-08-06 11:40 UTC
Labels: 1_bug, 3_duplicate
