### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by gkrzton** [frozn/TipTac#332] opened 2024-08-14 20:07 UTC
### Describe the bug

Message: ...nterface/AddOns/TipTacItemRef/libs/LibItemString.lua:321: attempt to call field 'SurfaceArgs' (a nil value)
Time: Wed Aug 14 22:05:42 2024
Count: 1
Stack: ...nterface/AddOns/TipTacItemRef/libs/LibItemString.lua:321: attempt to call field 'SurfaceArgs' (a nil value)
[string "@Interface/AddOns/TipTacItemRef/libs/LibItemString.lua"]:321: in function <...nterface/AddOns/TipTacItemRef/libs/LibItemString.lua:316>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/TipTacItemRef/ttItemRef.lua"]:2417: in function `item'
[string "@Interface/AddOns/TipTacItemRef/ttItemRef.lua"]:1282: in function <Interface/AddOns/TipTacItemRef/ttItemRef.lua:1271>
[string "@Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua"]:389: in function <...libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:387>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:61: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:56>
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:81: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:77>
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:117: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:107>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:142: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:135>
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:288: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:238>
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:235: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:234>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetAction'
[string "@Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua"]:1126: in function `SetTooltip'
[string "@Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua"]:1468: in function <.../AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:1463>
[string "=[C]"]: ?

Locals: self = <table> {
 ITEM_LEVEL_PATTERN = "Item Level (%d+)"
 ITEMSTRING_PROPERTY_INDEX = <table> {
 }
 TIMEWARPED_LEVEL_ADJUST = <table> {
 }
 UPGRADED_LEVEL_ADJUST = <table> {
 }
 ITEMSTRING_PATTERN = "(item:[^|]+)"
 ScanTip = LibItemStringScanTip {
 }
 TOOLTIP_MAXLINE_LEVEL = 5
 REVISION = 4
 TIMEWARPED_WARFORGED_LEVEL_ADJUST = <table> {
 }
}
itemLink = "[Refreshing Healing Potion |A:Professions-ChatIcon-Quality-Tier1:17:15::1|a]"
tooltipData = <table> {
 dataInstanceID = 6520
 type = 0
 isAzeriteEmpoweredItem = false
 isAzeriteItem = false
 id = 191378
 hyperlink = "[Refreshing Healing Potion |A:Professions-ChatIcon-Quality-Tier1:17:15::1|a]"
 isCorruptedItem = false
 lines = <table> {
 }
}
(*temporary) = nil
(*temporary) = <table> {
 dataInstanceID = 6520
 type = 0
 isAzeriteEmpoweredItem = false
 isAzeriteItem = false
 id = 191378
 hyperlink = "[Refreshing Healing Potion |A:Professions-ChatIcon-Quality-Tier1:17:15::1|a]"
 isCorruptedItem = false
 lines = <table> {
 }
}
(*temporary) = "attempt to call field 'SurfaceArgs' (a nil value)"
LIS = <table> {
 ITEM_LEVEL_PATTERN = "Item Level (%d+)"
 ITEMSTRING_PROPERTY_INDEX = <table> {
 }
 TIMEWARPED_LEVEL_ADJUST = <table> {
 }
 UPGRADED_LEVEL_ADJUST = <table> {
 }
 ITEMSTRING_PATTERN = "(item:[^|]+)"
 ScanTip = LibItemStringScanTip {
 }
 TOOLTIP_MAXLINE_LEVEL = 5
 REVISION = 4
 TIMEWARPED_WARFORGED_LEVEL_ADJUST = <table> {
 }
}

### Version of TipTac Reborn

24.08.05

### Flavor/Version of WoW

11.0.2

**Comment by spectre013** [comment] 2024-08-15 02:13
Turn of the ItemRef part and TipTac will work for now.

**Comment by frozn** [comment] 2024-08-19 00:11
Thanks for reporting this! 👍

Calling `TooltipUtil.SurfaceArgs()` is obsolete (since df 10.1.0) and can be removed. The fix will be included in the next release.

Duplicate of #330.

**Closed** 2024-08-19 00:11 UTC
Labels: 1_bug, 3_duplicate
