### ISSUE TITLE
Mouse over crafting mat icon issue

### ISSUE THREAD

**Issue by JnX3r** [frozn/TipTac#120] opened 2022-11-02 10:11 UTC
25x Interface/AddOns/TipTacItemRef/ttItemRef.lua:772: attempt to call field 'GetRecipeReagentItemLink' (a nil value)

**Comment by frozn** [comment] 2022-11-02 19:39
Duplicate of #109. Fixed with release [v22.10.30](https://github.com/frozn/TipTac/releases/tag/v22.10.30). Nevertheless thanks for reporting this! 👍

**Closed by frozn** 2022-11-02 19:39 UTC
Labels: 1_bug, 3_duplicate
