### ISSUE TITLE
Copying Talent Loadout Error - ADDON_ACTION_FORBIDDEN

### ISSUE THREAD

**Issue by PositiveRoleModel** [frozn/TipTac#130] opened 2022-11-16 09:36 UTC
**Describe the bug**
Using the in-game feature on the Talent Pane dropdown menu: Share (copy to clipboard) this error pops up and the UI blocks it from happening listing TipTac as the add-on causing the error

**To Reproduce**
1. Go to 'Talents'
2. Click on 'Share (copy to clipboard) in the dropdown menu in the lower left of the talent pane UI'
3. See error

**WoW Retail ver10.0.2
 
The Error text:
4x [ADDON_ACTION_FORBIDDEN] AddOn 'TipTac' tried to call the protected function 'CopyToClipboard()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `CopyToClipboard'
[string "@Interface/AddOns/Blizzard_ClassTalentUI/Blizzard_ClassTalentTalentsTab.lua"]:443: in function `callback'
[string "@Interface/SharedXML/LoadSystem/LoadSystemTemplates.lua"]:26: in function <...terface/SharedXML/LoadSystem/LoadSystemTemplates.lua:17>
[string "=(tail call)"]: ?
[string "@Interface/SharedXML/SharedUIPanelTemplates.lua"]:2421: in function `SetSelectedValue'
[string "@Interface/SharedXML/SharedUIPanelTemplates.lua"]:2373: in function `func'
[string "@Interface/SharedXML/UIDropDownMenu.lua"]:1007: in function `UIDropDownMenuButton_OnClick'
[string "*UIDropDownMenuTemplates.xml:136_OnClick"]:1: in function <[string "*UIDropDownMenuTemplates.xml:136_OnClick"]:1>

**Comment by frozn** [comment] 2022-11-17 19:48
Unfortunately I can't reproduce this error on retail or ptr, both on patch 10.0.2. 🤔

**Comment by 0xjc** [comment] 2022-11-19 18:51
I am able to repro this issue on the beta client with only TipTac addons enabled.
- Open talents pane
- Change a talent
- Apply changes
- Click Share (copy to clipboard) -> above error occurs, talent string not copied

**Comment by frozn** [comment] 2022-11-20 23:41
@0xjc: On PTR (10.0.2) I only enabled TipTac with default options and I didn't get this error with your described procedure. I don't have a clue what's going on here. :-(

**Comment by frozn** [comment] 2023-01-23 22:46
Should be fixed with latest release [v23.01.23](https://github.com/frozn/TipTac/releases/tag/v23.01.23-release). Please try again with this version.

**Closed** 2023-03-07 22:40 UTC
Labels: 1_bug, 2_to develop, 3_solved
