### ISSUE TITLE
lua error regarding quests

### ISSUE THREAD

**Issue by yourapple** [frozn/TipTac#119] opened 2022-11-02 07:58 UTC
1x Interface/AddOns/TipTacItemRef/ttItemRef.lua:756: attempt to index local 'link' (a nil value)
[string "@Interface/AddOns/TipTacItemRef/

**Comment by frozn** [comment] 2022-11-02 19:04
Duplicate of #109. Already fixed with release [v22.10.30](https://github.com/frozn/TipTac/releases/tag/v22.10.30).

Nevertheless thanks for reporting this! 👍

**Comment by frozn** [comment] 2022-11-02 19:32
Fixed it. Here's the current dev version:

[TipTac-dev.zip](https://github.com/frozn/TipTac/files/9923587/TipTac-dev.zip)

Will be included in the next release. Can you test with this version if the error is gone? Thanks!

**Comment by yourapple** [comment] 2022-11-03 06:05
Thank you

**Closed** 2022-11-11 23:27 UTC
Labels: 1_bug, 2_to develop, 3_solved
